INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('mitski-qU5D49kfNEM','Mitski - I Don','qU5D49kfNEM',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-_tV5Mn_raxk','Mitski - I Don','_tV5Mn_raxk',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-So0NYg0I0CI','Mitski - I Guess','So0NYg0I0CI',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-1-kO12tP3SE','Mitski - I Want You','1-kO12tP3SE',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-A2LEaF1jCeA','Mitski - I Will','A2LEaF1jCeA',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-83yYI2bWN0U','Mitski - If I Leave','83yYI2bWN0U',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski--KttTf9jyT8','Mitski - Jobless Monday','-KttTf9jyT8',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-aBJk6oDsulQ','Mitski - Last Words of a Shooting Star','aBJk6oDsulQ',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-21SM9Kxw3mA','Mitski - Lightning','21SM9Kxw3mA',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-Bfurc6KcMwk','Mitski - Liquid Smooth','Bfurc6KcMwk',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-1unkUUKwoqA','Mitski - Lonesome Love','1unkUUKwoqA',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-DlVKgdhYV6g','Mitski - Love Me More','DlVKgdhYV6g',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-QuRQREn-mUo','Mitski - Nobody','QuRQREn-mUo',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-Rr90U7bPoiE','Mitski - I Bet on Losing Dogs','Rr90U7bPoiE',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-V3K503Qf2dU','Mitski - My Love Mine All Mine','V3K503Qf2dU',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-3vgnnN_N_3o','Mitski - Washing Machine Heart','3vgnnN_N_3o',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-1p8S7vH_G5M','Mitski - First Love / Late Spring','1p8S7vH_G5M',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-4zSHu-fY-yM','Mitski - Heaven','4zSHu-fY-yM',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-pq65f3k9J4k','Mitski - I','pq65f3k9J4k',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-2g9f_FQYeF4','Mitski - Happy','2g9f_FQYeF4',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-Yuu1qC99T2U','Mitski - Lightning','Yuu1qC99T2U',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-yP54cnKzoFI','Mitski - Townie','yP54cnKzoFI',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-kZtLeFs5fCA','Mitski - Your Best American Girl','kZtLeFs5fCA',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-QhcLlBWIlEE','Mitski - Real Men','QhcLlBWIlEE',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-DXHSKLGIrrI','Mitski - Strawberry Blond','DXHSKLGIrrI',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-HAFBY8Wskbk','Mitski - Me and My Husband','HAFBY8Wskbk',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-2e4SiznTXKU','Mitski - stay soft','2e4SiznTXKU',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski--92dl4IUHQQ','Mitski - Should','-92dl4IUHQQ',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-WsPyOVUb_e8','Mitski - The Only Heartbreaker','WsPyOVUb_e8',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-c_LIHi670tI','Mitski - Valentine, Texas','c_LIHi670tI',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('melanie-p_6mHl_8_vU','Melanie Martinez - Death','p_6mHl_8_vU',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-3oSHhZmc_o0','Melanie Martinez - VOID','3oSHhZmc_o0',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-xuhIFRdszbM','Melanie Martinez - TUNNEL VISION','xuhIFRdszbM',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-z61w9HxJAb0','Melanie Martinez - FAERIE SOIRÉE','z61w9HxJAb0',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-WcEwxk6hZnI','Melanie Martinez - LIGHT SHOWER','WcEwxk6hZnI',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-bf6hlhpsgsg','Melanie Martinez - SPIDER WEB','bf6hlhpsgsg',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie--K-AXrTLqPU','Melanie Martinez - LEECHES','-K-AXrTLqPU',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-iW1djiqFzAk','Melanie Martinez - BATTLE OF THE LARYNX','iW1djiqFzAk',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-8Y3BXWkG-Bk','Melanie Martinez - THE CONTORTIONIST','8Y3BXWkG-Bk',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-jieiS-k5ziA','Melanie Martinez - POSSESSION','jieiS-k5ziA',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-828v-qOLlR4','Melanie Martinez - WHITE BOY WITH A GUN','828v-qOLlR4',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-Y_Bkb0kqiaA','Melanie Martinez - DISNEY PRINCESS','Y_Bkb0kqiaA',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-7WxtPVjfSXo','Melanie Martinez - GRUDGES','7WxtPVjfSXo',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-zAKukOBNVQE','Melanie Martinez - MONOPOLY MAN','zAKukOBNVQE',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-aVMci3Ub_FQ','Melanie Martinez - AVOIDANT','aVMci3Ub_FQ',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-bd33vyAPO-k','Melanie Martinez - MONOLITH','bd33vyAPO-k',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-7M2aspTiMSc','Melanie Martinez - WEIGHT WATCHERS','7M2aspTiMSc',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-OJVcccvaC9k','Melanie Martinez - THE PLAGUE','OJVcccvaC9k',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-G5uU3OigluM','Melanie Martinez - BATSHIT INTELLIGENCE','G5uU3OigluM',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-xHFPyE0wmAs','Melanie Martinez - GUTTER','xHFPyE0wmAs',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-Kst-f5zYWJI','Melanie Martinez - UNCANNY VALLEY','Kst-f5zYWJI',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-WPkgGvBfRPw','Melanie Martinez - THE VATICAN','WPkgGvBfRPw',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-RFIpskhn5XM','Melanie Martinez - HELL','RFIpskhn5XM',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-nKFLJlnwYzU','Melanie Martinez - CHATROOM','nKFLJlnwYzU',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie--EUfhQJuYK4','Melanie Martinez - THE LAST TWO PEOPLE ON EARTH','-EUfhQJuYK4',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-RfPm4wc1rj4','Melanie Martinez - Dead to Me','RfPm4wc1rj4',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-f3-mLw9AqhE','Melanie Martinez - Bittersweet Tragedy','f3-mLw9AqhE',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-mh-E_c6TEv0','Melanie Martinez - Cry Baby','mh-E_c6TEv0',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-Fu5mBO3pH8k','Melanie Martinez - Dollhouse','Fu5mBO3pH8k',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-WnJLpABeZD8','Melanie Martinez - Sippy Cup','WnJLpABeZD8',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-Y1X6dCCtzOc','Melanie Martinez - Carousel','Y1X6dCCtzOc',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-3I10gH32Xc8','Melanie Martinez - Alphabet Boy','3I10gH32Xc8',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-_RyiXOoDijk','Melanie Martinez - Soap','_RyiXOoDijk',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-vD0ZkIibN54','Melanie Martinez - Training Wheels','vD0ZkIibN54',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-5w_hsen-fDs','Melanie Martinez - Pity Party','5w_hsen-fDs',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-W3CwR9GPjOc','Melanie Martinez - Tag, You','W3CwR9GPjOc',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-MfkD3X8UEr4','Melanie Martinez - Milk and Cookies','MfkD3X8UEr4',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-4CVa3z1kt3E','Melanie Martinez - Pacify Her','4CVa3z1kt3E',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-Av8k0aCdw6A','Melanie Martinez - Mrs. Potato Head','Av8k0aCdw6A',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-UaYBbzUXGzM','Melanie Martinez - Mad Hatter','UaYBbzUXGzM',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-tp8WZuJZh8o','Melanie Martinez - Play Date','tp8WZuJZh8o',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-QWM5BsDjXuI','Melanie Martinez - Teddy Bear','QWM5BsDjXuI',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-WkMLrMAudzk','Melanie Martinez - Cake','WkMLrMAudzk',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-2IHcXyYmZu0','Melanie Martinez - Gingerbread Man','2IHcXyYmZu0',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-2FV-clvIwPI','Melanie Martinez - Wheels on the Bus','2FV-clvIwPI',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-d5rL9pZO6e0','Melanie Martinez - Class Fight','d5rL9pZO6e0',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-TmqET0WZZsA','Melanie Martinez - The Principal','TmqET0WZZsA',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-tkjI7eVY0bw','Melanie Martinez - Show & Tell','tkjI7eVY0bw',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-jC0VO5uJV6w','Melanie Martinez - Nurse','jC0VO5uJV6w',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-_VI7dehRwy0','Melanie Martinez - Drama Club','_VI7dehRwy0',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-SneWdW4P7cQ','Melanie Martinez - Strawberry Shortcake','SneWdW4P7cQ',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-0vM7nweKJmk','Melanie Martinez - Lunchbox Friends','0vM7nweKJmk',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-983KYWPqszs','Melanie Martinez - Orange Juice','983KYWPqszs',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-82s9TxIbnbQ','Melanie Martinez - Detention','82s9TxIbnbQ',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-8p60STDz_6w','Melanie Martinez - Teacher','8p60STDz_6w',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-y-8JnM3MJVk','Melanie Martinez - High School Sweethearts','y-8JnM3MJVk',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-ZqaH-MXRSac','Melanie Martinez - Recess','ZqaH-MXRSac',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-EnHp2lqvhHI','Melanie Martinez - Fire Drill','EnHp2lqvhHI',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-fwCAy90o3Zs','Melanie Martinez - Copy Cat (feat. Tierra Whack)','fwCAy90o3Zs',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-VQdMRFMIRKE','Melanie Martinez - Notebook','VQdMRFMIRKE',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-JlyVu751UFM','Melanie Martinez - Test Me','JlyVu751UFM',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-aoh4wIG-RLI','Melanie Martinez - Brain & Heart','aoh4wIG-RLI',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-g3wpxaJMRHc','Melanie Martinez - Numbers','g3wpxaJMRHc',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-LBBsKb1bMwQ','Melanie Martinez - Glued','LBBsKb1bMwQ',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-pK-u6i7hbPg','Melanie Martinez - Field Trip','pK-u6i7hbPg',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-0tHRHtxLQgU','Melanie Martinez - The Bakery','0tHRHtxLQgU',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('melanie-jAAJ4S5ayXo','Melanie Martinez - DEATH','jAAJ4S5ayXo',0,'POP','MELANIE',NULL,NULL,NULL,NULL,NULL,true),
('daikinez-wYOmfiMrrUg','Daikinez - Correntes Atemporais (Ekko & Jinx)','wYOmfiMrrUg',0,'DAIKINEZ','DAIKINEZ',NULL,NULL,NULL,NULL,NULL,true),
('daikinez-3usWjQ48tSk','Daikinez - Pela Honra (Zenitsu) ','3usWjQ48tSk',0,'DAIKINEZ','DAIKINEZ',NULL,NULL,NULL,NULL,NULL,true),
('daikinez-P6J1-ncXwpE','Daikinez - Viverei até o fim (Akaza) ','P6J1-ncXwpE',0,'DAIKINEZ','DAIKINEZ',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;