INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('anirap-ewCWhNeRGv4','♪ Fundadores da Toman | A Nova Era | ESPECIAL 300K PT 2 | URT  (@HunterMsc)','ewCWhNeRGv4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-6xErMAa6ZF0','♪ RAGNAROK | Deuses VS Humanos | ESPECIAL 300K PT 1 | URT  (@HunterMsc )','6xErMAa6ZF0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-e-HHrS8sBAQ','♪ Buda | Pela Humanidade | AniRap (@HunterMsc)','e-HHrS8sBAQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-HuBo6a_6L80','♪ Mikey/Manjiro Sano | O Líder Invencível | AniRap (Prod. WB)','HuBo6a_6L80',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-3P_EEEqUctk','♪ Desabafo Escanor | Eu Vou Morrer Feliz | AniRap (@HunterMsc)','3P_EEEqUctk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-NuP_wPcjafE','♪ Feridas | Luffy, Ace e Sabo | Feat: @ishidaoficial   e @OkabeOficial | AniRap  (@HunterMsc)','NuP_wPcjafE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-2CniFpmJ-Aw','♪ Traumas De Um Herói | Midoriya, Bakugou e Todoroki | AniRap (@HunterMsc)','2CniFpmJ-Aw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5v1FogPQ5MI','♪ Draken/Ken Ryuguki | Uma Bela Cicatriz | AniRap (Prod. WB)','5v1FogPQ5MI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-JFDQ8SZU9hk','♪ Desabafo Eren Yeager | O Preço da Liberdade | AniRap (@HunterMsc)','JFDQ8SZU9hk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-q_P67p_v_Lw','♪ Adão | Pai da Humanidade | AniRap (@HunterMsc)','q_P67p_v_Lw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-GF-urGMT8EY','♪ Meus Pecados | AniRap (@HunterMsc)','GF-urGMT8EY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-XhBc9cEoJy8','♪ Diante do Fim | Meliodas, Gon, Itadori, Eren... | AniRap (Prod.WB)','XhBc9cEoJy8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-BcvEiuGJFT4','♪ Megumi Fushiguro | 10 Sombras | AniRap (@HunterMsc)','BcvEiuGJFT4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-fYQPuBoe02A','♪ Desabafo Kawaki | Maldita Infância | AniRap (@HunterMsc)','fYQPuBoe02A',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-FeBLGp3ADdA','♪ Desabafo Akatsuki | Corrompidos | AniRap (@HunterMsc)','FeBLGp3ADdA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LgcmewQrt6U','Rap do Zeke Yeager 『 Shingeki No Kyojin 』 | SEREI A CHAVE | AniRap (@HunterMsc)','LgcmewQrt6U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-RV91TljQOHQ','Rap dos 9 Titãs Primordiais 『 Shingeki no Kyojin 』| ESPECIAL 200K | URT (@HunterMsc)','RV91TljQOHQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Fd62Haro6QI','Rap - Sinto Muito 『 Hikigaya, Meliodas, Yuu, Eren... 』 | SadMix 1 | AniRap & @Shiny_sz','Fd62Haro6QI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-pe028sVUJiA','Rap do Jintan 『 AnoHana 』 | NÓS TE ACHAMOS | AniRap (@HunterMsc)','pe028sVUJiA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-HzEgDpWKFag','Rap do Mael 『 Nanatsu no Taizai 』 | HÍBRIDO DE GUERRA | AniRap (@HunterMsc)','HzEgDpWKFag',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap--t6gNHjzaL8','Rap do Ragnar 『 Vikings 』 | O HOMEM MAIS PERIGOSO DO MUNDO | AniRap (@HunterMsc)','-t6gNHjzaL8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-RsFjJHZrBpA','Rap do Overhaul 『 Boku no Hero Academia 』 | EU SEREI A PESTE | AniRap','RsFjJHZrBpA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-qYfuJBqmB84','♪ Escolhi Não Ser Ninguém | AniRap (@HunterMsc)','qYfuJBqmB84',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-cQKjL2tNQlk','♪ Desabafo Reiner Braun | Personalidades | AniRap (@HunterMsc)','cQKjL2tNQlk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-gp3woMiNrpk','Rap do Arima Kousei 『 Shigatsu Wa Kimi no Uso 』 | A DOR DO SILÊNCIO | AniRap (Prod. @prod.mkbeats​)','gp3woMiNrpk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-FWNXd8Doqlo','Rap do Itadori/Sukuna『 Jujutsu Kaisen 』 | VOCÊ NÃO VAI PREDOMINAR | AniRap (Prod. @prod.mkbeats)','FWNXd8Doqlo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-7xPcnP7dP2M','Rap do Deidara 『 Naruto Shippuden 』 | O ARTISTA RENEGADO | AniRap (Prod. @Gabriza)','7xPcnP7dP2M',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-7a7cntJd0J0','Rap do Eren 『 Shingeki no Kyojin 』Part. 1 | TATAKAE | AniRap (@HunterMsc)','7a7cntJd0J0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Z5k1r7NU8-w','Rap do Zeldris 『 Nanatsu no Taizai 』 | O PRÓXIMO REI | (@HunterMsc)','Z5k1r7NU8-w',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-rmi-YfE0b3U','Rap - Desabafo 8 『 Tatsumi 』 | Mortes | AniRap  (@HunterMsc)','rmi-YfE0b3U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-FknGm-G88r4','Rap - Redenção 『 Endeavor, Yato e Kakashi 』 | AniRap | (@HunterMsc)','FknGm-G88r4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-vXZV4J2BhOk','Rap do Estarossa 『 Nanatsu no Taizai 』 | ENTRE DOIS LADOS | (@Prod Hunter)','vXZV4J2BhOk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-W5UvMYGejSc','Rap do Sasori 『 Naruto Shippuden 』 | ESCORPIÃO SOLITÁRIO | AniRap (@HunterMsc)','W5UvMYGejSc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-2h6gyEnxrqU','Rap do Edward Elric 『 Fullmetal Alchemist 』 | PECADOS DO PASSADO | AniRap (@HunterMsc)','2h6gyEnxrqU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-i1cGuhivHuk','Rap do Oreki Houtarou『 Hyouka 』 | Cansaço Mental | Feat: @Gabriza | AniRap (@HunterMsc)','i1cGuhivHuk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-u6XWRzA1iQo','Rap do Levi 『 Shingeki no Kyojin 』 | O DEMÔNIO DOS TITÃS | AniRap (@HunterMsc )','u6XWRzA1iQo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-00am5j7Yfj4','Rap do Kakashi 『 Naruto Shippuden 』 | POUPADO PELA MORTE | AniRap (Prod. Hunter)','00am5j7Yfj4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-yzg6WV1oFbs','Rap do Ray 『 The Promissed Neverland 』 | MINHA VINGANÇA | AniRap (Prod. Hunter)','yzg6WV1oFbs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-JKoVrwuJuHA','Rap do Hikigaya 『 Oregairu 』 | PRESO EM MINHA SOLIDÃO | AniRap e @MTD  (Prod. Hunter)','JKoVrwuJuHA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-1XC2Pao1z1A','Rap - DESABAFO DA GERAÇÃO 『 KNB 』 |Estou Quebrado| AniRap e @ishidaoficial  (Prod. Hunter)','1XC2Pao1z1A',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-zKR7YijXk6A','Rap do Satoru 『 Erased 』 | É POR VOCÊ | AniRap (Prod. Hunter)','zKR7YijXk6A',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-aowXDJuPiPQ','Rap dos 7 Pecados Capitais 『 Nanatsu no Taizai 』| URT (@HunterMsc)','aowXDJuPiPQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-_eAycoMpYH0','Rap do Yuu Otosaka 『 Charlotte 』 | Cicatrizes | AniRap (Prod. Hunter)','_eAycoMpYH0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-BNAIkjwoBaM','Rap dos 10 Mandamentos 『 Nanatsu no Taizai 』|ESPECIAL DE 100K| AniRap (Prod. Hunter)','BNAIkjwoBaM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-6dThsA3lc8E','Rap do Kisame『 Naruto Shippuden 』| Renegado Espadachim | AniRap (Prod. Hunter)','6dThsA3lc8E',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-AEc65sIJMeo','Rap - Por que estou vivo?『 Edward Elric, Sasuke & Okabe 』|Feat: @VitchBeats  e @off_Tsuu | AniRap','AEc65sIJMeo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-mR5h1OxiRgE','♪ Desabafo Kira | Um Deus Incompreendido | AniRap (@Prod Hunter)','mR5h1OxiRgE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-uMP_1jv_RLU','Rap - Sociopatas 『 Sasori, Ayanokoji, Ulquiorra 』| Feat: @Gabriza   | AniRap (Prod. Hunter)','uMP_1jv_RLU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5bfpWKYvSe8','Rap do Obito 『 Naruto Shippuden 』| Eu Não Sou Ninguém | AniRap (Prod. Hunter)','5bfpWKYvSe8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-62UqWxxGeeg','Rap do Dabi 『 Boku no Hero 』| O Filho Imperfeito | AniRap (Prod. WB Beats)','62UqWxxGeeg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LGaR_0Y9_Rg','Rap - Kira e L 『 Death Note 』| A Verdadeira Justiça | AniRap e @Flash Beats  (Prod. Hunter)','LGaR_0Y9_Rg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-_loTq8npqFk','Rap - Afastado de Todos 『 Arima, Hikigaya & Oreki 』 |Feat: @Gabriza  | AniRap','_loTq8npqFk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-3bQp5RAXdEA','Rap do Indra 『 Naruto Shippuden 』 |O Poder Absoluto| AniRap (Prod. WB Beats)','3bQp5RAXdEA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-H7T5quSzaWg','Rap do Itachi 『 Naruto Shippuden 』 |Pelo Meu Irmão| AniRap (Prod. Hunter)','H7T5quSzaWg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-tNh1nfgXvRg','♪ Desabafo Boruto | Sombra do Hokage | AniRap (@HunterMsc)','tNh1nfgXvRg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-K8FlkMsuc54','Rap - Eu Decido Meu Destino『 Killua, Todoroki, Meliodas & Mitsuki 』 | URT (Prod. Hunter)','K8FlkMsuc54',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-0G1fRtbehks','Rap do Shinichi 『 Parasyte/Kiseijuu 』 |Não consigo sentir| AniRap (Prod. Hunter)','0G1fRtbehks',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-3va2HAvhG54','Rap do Sasuke 『 Naruto Shippuden 』 | Hokage das Sombras | AniRap (@HunterMsc)','3va2HAvhG54',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-tbuOWXj6cUk','Rap - Tudo que eu passei 『 Hikigaya, Yuu, Meliodas, Kakashi... 』 | AniRap','tbuOWXj6cUk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-l6gOcxjragg','Rap - Eu sou a cura 『 Kira, Overhaul e Madara 』 | AniRap (Prod. Hunter)','l6gOcxjragg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-rWifpHfMJ8E','Rap - Pela Paz 『 Jiraya, Nagato e Naruto 』 | AniRap (Prod. Hunter)','rWifpHfMJ8E',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-E-spXXargW0','Rap - Desabafo 5 『 Akashi Seijuro 』 |Quem eu sou?| Ft: Ishida | AniRap','E-spXXargW0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Zup6Ms9LRuQ','Rap - Ferida Aberta 『 Jintan, Ishida & Edward Elric 』 | AniRap','Zup6Ms9LRuQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-XZQ7z0Q7Wl4','Rap - Desabafo 『 Yuu, Meliodas, Itachi, Yato... 』 | ESPECIAL 50K | AniRap','XZQ7z0Q7Wl4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-QpQf2QCSAtQ','Rap do Sasori 『 Naruto Shippuden 』 O Titeleiro Renegado| AniRap','QpQf2QCSAtQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-cx0vKf-TWzM','Rap do Akashi 『 Kuroko no Basket 』 |Dupla Personalidade| AniRap','cx0vKf-TWzM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-crP4vUAEkVs','Rap - Sofrimento Interno『 Ban, Todoroki & Yuu 』 | AniRap','crP4vUAEkVs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-MYQzy37SJas','Rap - Traumas 『 Naruto Shippuden 』 |Feat: Ishida| AniRap','MYQzy37SJas',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-dTIuMRYAJBQ','Rap - Aquele Momento 『 Ban, Edward Elric & Itachi 』 |Feat: Ishida| AniRap','dTIuMRYAJBQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-kdsGyqmkBQk','Rap - Meliodas, Estarossa e Zeldris 『 Nanatsu no Taizai 』 |Minha Decisão| AniRap','kdsGyqmkBQk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-mzf-VlyqHtk','Rap do Inosuke 『 Kimetsu no Yaiba 』 |Demon Slayer Selvagem| AniRap','mzf-VlyqHtk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-jX8RTEC0UFE','Rap - Desabafo 2 『 Bakugou Katsuki 』 |Me Sinto Fraco Também| AniRap','jX8RTEC0UFE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-XJffF7BYFsA','Rap - Desabafo 1 『 Aomine Daiki 』 |Estou Perdendo o Controle| AniRap','XJffF7BYFsA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-tesjw5rIYis','Rap do Senku 『 Dr. Stone 』 |Pela Ciência| AniRap','tesjw5rIYis',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-xOVD2P9gURs','Rap do Madara 『 Naruto Shippuden 』 |A Verdadeira Paz| AniRap','xOVD2P9gURs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-uyZXfmEs9Lw','Rap do Hikigaya 『 OreGairu』 Feat: MTD |Minha Solidão| AniRap','uyZXfmEs9Lw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-1LMR4M2tNSU','Rap - Thor, Capitão América e Homem de Ferro 『 Ultimato 』 |Nossa chance| AniRap','1LMR4M2tNSU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-3MUzbxoOH2w','Rap do Ishida Shoya 『 Koe no Katachi 』 |Me Desculpa| AniRap','3MUzbxoOH2w',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-S0l5VBP-1mM','Rap do Robin 『 Damian Wayne 』 |O Herdeiro do Morcego| AniRap','S0l5VBP-1mM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-me3xsa5v9Rk','Rap - Shisui e Itachi 『 Naruto 』 |Pela Paz| AniRap & Flash Beats','me3xsa5v9Rk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-u8bkquYwmT4','Rap - Caçador 『 Goblin Slayer, Stain & Chara 』| ESPECIAL 20K | AniRap','u8bkquYwmT4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-nTZf6dlmcWs','Rap do Jintan 『 AnoHana 』 |Me Perdoe| AniRap','nTZf6dlmcWs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-soFNnmqa2MY','Rap - Incapaz 『 Meliodas e Ban 』 |Feat: MTD| AniRap','soFNnmqa2MY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap--s09a9beLjU','Rap - Solidão 2 『 Gaara, Yuu & Kaneki 』 | AniRap','-s09a9beLjU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-96V9hrcnHJA','Rap do Zeldris 『 Nanatsu no Taizai 』 |O príncipe do Inferno| AniRap','96V9hrcnHJA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-WYT4GRsSrtU','Rap do Tatsumi 『 Akame Ga Kill』 |Vou limpar essa Capital| AniRap','WYT4GRsSrtU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-qCv_HoTbUQw','Rap - Orgulho no Topo 『 Akashi, Vegeta & Bakugou 』 |Especial de 10K|  AniRap','qCv_HoTbUQw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-rZlgzzJH6Cs','Rap - Solidão 『 Ishida, Jintan & Hikigaya 』 |Ft: VMZ| AniRap','rZlgzzJH6Cs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-73siE1J5j2k','Rap do Near 『 Death Note 』 |N assumirá| AniRap','73siE1J5j2k',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ENMCK1LwpPY','Rap do Geno Sans 『 Aftertale 』 |Pra isso sobrevivo| AniRap','ENMCK1LwpPY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-FrICD6sU0Zc','Rap do Homem Aranha 『 De volta ao Lar/ Guerra Infinita 』 |Até o dia da minha morte| AniRap','FrICD6sU0Zc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-QStWKIX863o','Minha DISS | Rap Geek','QStWKIX863o',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-9dbQgdB0SfQ','Rap - Itachi e Kisame 『 Naruto 』 Ft. Flash Beats |Meu passado| AniRap','9dbQgdB0SfQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-hdcKhyYDo00','Rap do Pain/Nagato 『 Naruto Shippuden 』 |Farei todos entender| AniRap','hdcKhyYDo00',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ROfMY-CGAoA','Rap - Manipulador 『 Ayanokouji, Obito, Chara 』 |  AniRap','ROfMY-CGAoA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-HFn1iUFo5oI','Rap do Bakugou 『 Boku no Hero』 |Serei o maior herói|  AniRap','HFn1iUFo5oI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-f0OH_yoMVCk','Rap do Arima『 Shigatsu Wa Kimi no uso 』 |Eu já não consigo escutar| AniRap','f0OH_yoMVCk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-geJXBIp-IoI','Rap do Hikigaya『 OreGairu 』|Escolhi ser Solitário| AniRap','geJXBIp-IoI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-wXjb4zlW-3Y','Rap do Yuu Otosaka『 Charlotte 』|Não retribuí em nada| AniRap','wXjb4zlW-3Y',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ZluANylfzNs','Rap - Minha Dor『 Animes 』 | AniRap','ZluANylfzNs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;