INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('anirap-VAJ9lKEHMfo','♪ Ragnarok 2 (Shuumatsu no Valkyrie) | Deuses VS Humanos  | URT','VAJ9lKEHMfo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-16IBpRFEoTI','♪ Madara Uchiha | Sonho Perfeito | AniRap','16IBpRFEoTI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-jv3eCTUDUBc','♪  Nova Geração (Maki, Hakari e Yuta) | AniRap','jv3eCTUDUBc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-l8_11f8qF9Y','♪ Honkai: Star Rail | Outra Noite | AniRap e @ishidaoficial','l8_11f8qF9Y',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-7Ozov4Ncli4','♪ Noah e Kaleb (Sense Life) | Parceria Formada | AniRap e @Shinysz','7Ozov4Ncli4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-6giaEUzek0o','♪ Kira (Death Note) | Castigo Divino | AniRap','6giaEUzek0o',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-7ObwSzXzT4k','♪ Doflamingo | Rei do Mundo | AniRap','7ObwSzXzT4k',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-p3MVh8-5nFo','♪ Higuruma Hiromi (Jujutsu Kaisen) | Tribunal | AniRap','p3MVh8-5nFo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-UxVHiPzeIbQ','♪ Toda Seigen (Tenkaichi) | Visão Sombria | AniRap','UxVHiPzeIbQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-6-N0j3GvoY4','♪ Scorpion (Mortal Kombat) | Espírito da Vingança | AniRap','6-N0j3GvoY4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-0nOtisVPlgw','♪ Leônidas | Esparta | AniRap','0nOtisVPlgw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-zIhvdpzepbM','♪ Kaneki e Rize | Escolhas | AniRap feat. @isisvasconcelllos','zIhvdpzepbM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-2M1FGPorLL8','♪ Hajime Kashimo | Eletricidade | AniRap','2M1FGPorLL8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-VmAOv5nRQ0k','♪ Satoru Gojo | O Mais Forte | AniRap','VmAOv5nRQ0k',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-EMp2QdO487w','♪ Basim (Assassin’s Creed Mirage) | A Justiça | AniRap','EMp2QdO487w',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-OlpXBeCgeqM','♪  Gojo e Geto | Caminhos Opostos | AniRap e @M4rkim','OlpXBeCgeqM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-A1W5jUqEAfs','♪ Gon | Inocência | AniRap','A1W5jUqEAfs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5qKnbKJMfXE','♪ Kaleb | OVER-DOSE | AniRap','5qKnbKJMfXE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-HJeuGSloQq8','♪ Bardock | Lenda Sayajin | AniRap','HJeuGSloQq8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-awCOeiqTX7s','♪ Ani & Morty | Bad Trip | AniRap','awCOeiqTX7s',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-r229gFVK3K0','♪ Blade (Honkai: Star Rail) | Vingança | AniRap e @AnnyTHN','r229gFVK3K0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-fosN9We9Nd4','♪ 3 Divindades | Mikey, Senju e South | AniRap','fosN9We9Nd4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-1uelv8yFO-I','♪ Musashi Miyamoto | Prodígio Espadachim | AniRap','1uelv8yFO-I',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5mlwHILJpVU','♪ Genya Shinazugawa | Fome de Oni | AniRap','5mlwHILJpVU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-lwzLDx_6vf8','♪ Acnologia | O Dragão do Apocalipse | AniRap','lwzLDx_6vf8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-l4czTNGqdB4','♪ Minoru Tanaka (Death Note) | O Novo Kira | AniRap','l4czTNGqdB4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-AFRkWeHVG_E','♪ Boruto Uzumaki | Karma | AniRap','AFRkWeHVG_E',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-XfjCeX5cgJk','♪ Shidou Ryusei | Demônio Egoísta | AniRap','XfjCeX5cgJk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5WwYeEg-D_E','♪ Desabafo Denji | Cercado por Mortos | AniRap','5WwYeEg-D_E',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-sUozdmBFBdc','♪ Hakari Kinji | Feiticeiro Imortal | AniRap','sUozdmBFBdc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-djlzewcsQUw','♪ Armin | Colossal | AniRap','djlzewcsQUw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-n_8RpXUwej8','♪ Vegeta Vs Granola | O Ego e a Vingança | AniRap e @ALBKMUSIC','n_8RpXUwej8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-CNWQVFBybK0','♪ Mitsuya | Dragão Gêmeo | AniRap','CNWQVFBybK0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-oNos7uJ6Qcg','♪ Nikola Tesla | A Luz da Humanidade | AniRap','oNos7uJ6Qcg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-WG9dfwyPyYA','♪ Lobo/Morte | ENTRE A VIDA E A MORTE | AniRap','WG9dfwyPyYA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Jo5EZ_ctrik','♪ Barou | Rei Absoluto | AniRap','Jo5EZ_ctrik',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-0CoRl33v-38','♪ Dabi | Fruto Podre | AniRap','0CoRl33v-38',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-fbiT7W3pEYo','♪ Taiju Shiba | Amém | AniRap','fbiT7W3pEYo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-V-rU-oYaQjw','♪ Bachira Meguru | O Monstro Egoísta | AniRap','V-rU-oYaQjw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-m84EyjhBgRg','♪ Batman e Capuz Vermelho | Pai e Filho | AniRap e Okabe','m84EyjhBgRg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LNFoSoaectw','♪ Desabafo Itadori Yuji | Desconstrução do Herói | Feat: @Gabriza e @DaaruiOficial | AniRap','LNFoSoaectw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ayn4JdjxZBQ','♪ Shibuya | Jujutsu Kaisen | ESPECIAL URT','ayn4JdjxZBQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-mRRDq8-bW8U','♪ Meliodas | Assault Mode | AniRap (@HunterMsc)','mRRDq8-bW8U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LIEFPrfMxXk','♪ Cesar/Kaiser | Angel of The Night | AniRap (@prod_wb)','LIEFPrfMxXk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-YMFp0Z3PdpQ','♪ Vegeta | Ego Superior | AniRap (@HunterMsc)','YMFp0Z3PdpQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-IVwjGX7hHbU','♪ Lideres | Tokyo Revengers | ESPECIAL 800K | URT','IVwjGX7hHbU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ugxgtYSBFXw','♪ Shigaraki | O Sucessor do Mal | AniRap (@HunterMsc )','ugxgtYSBFXw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-_JuqMBr90PY','♪ Kaigaku | Raio Negro | AniRap (Prod. Try)','_JuqMBr90PY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-7bR_zUhtfe8','♪ Falcão | Acerte Primeiro | AniRap (@HunterMsc)','7bR_zUhtfe8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-axCOZ5LOmUg','♪ Olhos Vendados | Gojo e Qin Shi Huang | AniRap e @VMZoficial','axCOZ5LOmUg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-qOboAGrnd2U','♪ Belzebu (Parte 1) | Amaldiçoado a Viver | AniRap (@HunterMsc)','qOboAGrnd2U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-C7wTN3AUxH0','♪ Até Demonios Choram | AniRap (Prod. Try)','C7wTN3AUxH0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-w5ZsLxdKvfA','♪ Katakuri | Futuro no Olhar | AniRap (@HunterMsc)','w5ZsLxdKvfA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-RCpAnaBAKX8','♪ Jack Hanma | Fome de poder | AniRap','RCpAnaBAKX8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5XmRCzuQ6L0','♪ Saitama | Soco Sério | AniRap (@HunterMsc )','5XmRCzuQ6L0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-qHfWqZEKNbE','♪ Zack Foster | Impulso Assassino | AniRap (@HunterMsc)','qHfWqZEKNbE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-4gKwtSuZp7Y','♪ Os Três Finais | Batman e Coringa | AniRap (@HunterMsc)','4gKwtSuZp7Y',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-vLddN4jFXsc','♪ Eddie Munson | O Meu Ano | AniRap','vLddN4jFXsc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-aa-gGernGLY','♪ Fushiguro Toji | O Assassino de Xamãs | AniRap (Prod. WB)','aa-gGernGLY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-nxXPc9eADkQ','♪ Capitão Pátria | O Único Homem no Céu | AniRap (Prod. WB)','nxXPc9eADkQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-QWdfCBbxpww','♪ Soldier Boy | Eu Sou Perfeito | AniRap','QWdfCBbxpww',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-P0_fHUvgpG0','♪ Homem-Aranha Superior | A Melhor Versão | AniRap (Prod. WB)','P0_fHUvgpG0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-zmBCBQ5R9Ww','♪ Aomine | Pantera Indomável | AniRap (@HunterMsc)','zmBCBQ5R9Ww',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5RSP1ENo044','♪ Hades | Uma Promessa | AniRap','5RSP1ENo044',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LdQqRTqic-c','♪ Coringa | Piada Macabra | AniRap (@HunterMsc)','LdQqRTqic-c',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ev1pHAvdcv0','♪ Toxina | Substância Nociva | AniRap & Okabe (@Prod Hunter)','ev1pHAvdcv0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ggE6XCp0kyY','♪ Goku Black | Nova Criação | AniRap (@HunterMsc )','ggE6XCp0kyY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-kFxyGsuKIPU','♪ Yuu Otosaka | Traumas | AniRap (Prod. @prod_wb  )','kFxyGsuKIPU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-JgWi9IdUzCA','♪ Mahito | A Essência da Alma | AniRap (@HunterMsc)','JgWi9IdUzCA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Kbi6ClG8H9U','♪ Sanemi e Genya | Caçada Violenta | AniRap e Flash Beats (@HunterMsc)','Kbi6ClG8H9U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-CZEnG7JQPzY','♪ Ban | Purgatório | AniRap (@HunterMsc)','CZEnG7JQPzY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-e8HLrcsR-U0','♪ Nagato/Pain | Um Deus | AniRap (@HunterMsc)','e8HLrcsR-U0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-QWKeRlu9KPg','♪ Capuz Vermelho | O Robin é Passado | AniRap (@HunterMsc)','QWKeRlu9KPg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-mKnybb5Q6FE','♪  Izana Kurokawa | O Irmão Esquecido | AniRap (Prod. Khellvyn)','mKnybb5Q6FE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-wS3CMIb-cNM','♪ BoJack Horseman | Vazio Existencial | AniRap','wS3CMIb-cNM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-reJ6If_HJ6s','♪ Gyutaro | O Lua Superior 6 | AniRap (@HunterMsc)','reJ6If_HJ6s',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-qNRg7Mi7kFA','♪ Anti-Venom | Caçando Minha Própria Raça | AniRap (@HunterMsc)','qNRg7Mi7kFA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-m4Y0HbwtHWk','♪ Eren Yeager | O Sacrifício Do Vilão | AniRap (@HunterMsc)','m4Y0HbwtHWk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-AEZ56qkZjIE','♪ Karma Akabane | Prodígio Assassino | AniRap (@HunterMsc)','AEZ56qkZjIE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-I9jsytSvjBU','♪ Raiden Tameemon | Meu Último Ataque | AniRap (@HunterMsc)','I9jsytSvjBU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-1qnrc9AhdnM','♪ Levi Ackerman | Minha Última Missão | AniRap (Prod. WB)','1qnrc9AhdnM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-CeIjag_cOc0','♪ Yoriichi e Kokushibo | Destinos Separados | AniRap e @M4rkim  (Prod. @prod_wb)','CeIjag_cOc0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-_hqHbBn_A9A','♪ Arthur Leywin | Um Novo Começo | AniRap (Prod. @prod_wb)','_hqHbBn_A9A',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-1Er-z8jAbOQ','♪ Desabafo Mikey/Manjiro Sano | Futuro Sombrio | AniRap (@HunterMsc)','1Er-z8jAbOQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-WktraZWNX9Q','♪ Sung Jin Woo | O Necromante | AniRap (@HunterMsc)','WktraZWNX9Q',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-crNPOJSdcHE','♪ Akaza | O Lua Superior 3 | AniRap (@HunterMsc )','crNPOJSdcHE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LmJ9e8S9OBg','♪ Destino Final | (JoJo','LmJ9e8S9OBg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-_D_UdWu6ri8','♪ Destino Final | (JoJo','_D_UdWu6ri8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-3JXUPKS7yCM','♪ Desabafo Subaru | Cansado de Voltar | AniRap (@HunterMsc)','3JXUPKS7yCM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-j2DPxHQ2SUc','♪ Zerofuku | O Deus da Miséria | AniRap (@HunterMsc)','j2DPxHQ2SUc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-53NIBnIrypU','♪ Kazutora | O Tigre Renegado | AniRap ( @Prod Hunter )','53NIBnIrypU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-d4igTdt2w4I','♪ Yuta Okkotsu | Minha Maldição | AniRap (Prod. WB)','d4igTdt2w4I',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-wzQAHRHvSBI','♪ Kakyoin | Eu Consegui Descobrir | AniRap (@HunterMsc)','wzQAHRHvSBI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ToL-Z0gpnXQ','♪ Sanemi Shinazugawa | O Vento Da Morte | AniRap (Prod. @prod_wb)','ToL-Z0gpnXQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-vrd3BMy62ak','♪ Joseph Joestar | Sua Próxima Frase | AniRap (@HunterMsc)','vrd3BMy62ak',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-RuHe2nBlliE','♪ Baji e Kazutora | Renegados da Toman | AniRap & @ishidaoficial  (@HunterMsc)','RuHe2nBlliE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-XMUff4YIbOc','♪ Desabafo Naruto | Adeus Kurama | AniRap (@HunterMsc)','XMUff4YIbOc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-2GzPHddgY6U','♪ Jack Estripador | O Mal Da Humanidade | AniRap (@Prod Hunter)','2GzPHddgY6U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-gpR7lQJMc9Y','♪ Ayanokoji | Um Psicopata Entre Vocês | AniRap (@HunterMsc)','gpR7lQJMc9Y',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-MGxqFRHl0W0','♪ Sakuta | Não Vou Esquecer | AniRap (Prod. @prod_wb)','MGxqFRHl0W0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;