INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('anirap-gEDfxssNzuA','Rap do Madara 『 Naruto 』|Só existe esse caminho| AniRap','gEDfxssNzuA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-8fXZSM0KN24','Rap - Kise e Aomine 『 Kuroko no Basket 』|Ft : Thor| AniRap','8fXZSM0KN24',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-xJwOHqCwzoo','Rap do Yato  『 Noragami  』|Eu já cansei| AniRap','xJwOHqCwzoo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-PP_Nl_tHg18','Rap - Quem eu sou ? 『 Shinichi e Kaneki 』AniRap','PP_Nl_tHg18',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-x-0ABAPBdco','Rap - Chara e Frisk  『 Undertale 』Feat: Thelfos | AniRap','x-0ABAPBdco',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-yQ6yz0fUXNA','Rap da Geração Milagrosa 『 Kuroko no Basket 』Feat : Descrição | ESPECIAL DE 1K !!!','yQ6yz0fUXNA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-15tKncMoxDc','Rap do Basil 『 Dragon Ball Super 』|Chutador do 9º Universo| AniRap','15tKncMoxDc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('rodrigozin-Lp961zLpKJ0','Rodrigo Zin - Edward Elric','Lp961zLpKJ0',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','edward','elric'],NULL,NULL,NULL,true),
('rodrigozin-fugKjEvQ9gs','Rodrigo Zin - Hyakkimaru (Dororo)','fugKjEvQ9gs',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','hyakkimaru','dororo'],NULL,NULL,NULL,true),
('rodrigozin-ZykvbPUzdTI','Rodrigo Zin - Shinji Ikari (Me Tirem Daqui)','ZykvbPUzdTI',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','shinji','ikari','tirem','daqui'],NULL,NULL,NULL,true),
('rodrigozin-wqhqHP2Uu_0','Rodrigo Zin - Re:Zero','wqhqHP2Uu_0',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','zero'],NULL,NULL,NULL,true),
('rodrigozin-lt2itTWpz_k','Rodrigo Zin - Shōyō Hinata (Haikyuu!!)','lt2itTWpz_k',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','shoyo','hinata','haikyuu'],NULL,NULL,NULL,true),
('rodrigozin-I5JIbfHa8tA','Rodrigo Zin - Izuku Midoriya (Part. Ardlez)','I5JIbfHa8tA',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','izuku','midoriya','part','ardlez'],NULL,NULL,NULL,true),
('rodrigozin--oAxFbAs-n4','Rodrigo Zin - Chainsaw Man','-oAxFbAs-n4',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','chainsaw','man'],NULL,NULL,NULL,true),
('rodrigozin-Epg3t6HaeFI','Rodrigo Zin - Aubrey (Omori)','Epg3t6HaeFI',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','aubrey','omori'],NULL,NULL,NULL,true),
('rodrigozin-MG_FxVYj7I4','Rodrigo Zin - Eren Yeager','MG_FxVYj7I4',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','eren','yeager'],NULL,NULL,NULL,true),
('rodrigozin--QBuXSGQ9fM','Rodrigo Zin - Roy Mustang','-QBuXSGQ9fM',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','roy','mustang'],NULL,NULL,NULL,true),
('rodrigozin-Dha4v8CQbm8','Rodrigo Zin - Mob','Dha4v8CQbm8',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','mob'],NULL,NULL,NULL,true),
('rodrigozin-BeNDfF0srwY','Rodrigo Zin - Crocodile','BeNDfF0srwY',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','crocodile'],NULL,NULL,NULL,true),
('rodrigozin-OGZGkZ_cr58','Rodrigo Zin - Soul Eater (Part. LexClash)','OGZGkZ_cr58',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','soul','eater','part','lexclash'],NULL,NULL,NULL,true),
('rodrigozin-sbCA35RY4RA','Rodrigo Zin & Matosu - Referências [Especial 25K de inscritos]','sbCA35RY4RA',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','matosu','referencias','especial','25k','inscritos'],NULL,NULL,NULL,true),
('rodrigozin-pKa5qh3iuBs','Rodrigo Zin - Darling (Part. Gabriel Rodrigues)','pKa5qh3iuBs',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','darling','part','gabriel','rodrigues'],NULL,NULL,NULL,true),
('rodrigozin-SuOKLeEnl_8','Rodrigo Zin x @Enygma_Music  - Erra Nunca','SuOKLeEnl_8',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','enygma','music','erra','nunca'],NULL,NULL,NULL,true),
('rodrigozin-VF6W9rUyuUs','Rodrigo Zin - Zenitsu Agatsuma','VF6W9rUyuUs',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','zenitsu','agatsuma'],NULL,NULL,NULL,true),
('rodrigozin-pWomJnHKWsE','Rodrigo Zin - Kyojuro Rengoku','pWomJnHKWsE',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','kyojuro','rengoku'],NULL,NULL,NULL,true),
('rodrigozin-La0vIRNOypQ','Rodrigo Zin - Capone Gang Bege ( One Piece )','La0vIRNOypQ',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','capone','gang','bege','one','piece'],NULL,NULL,NULL,true),
('rodrigozin-nkh02_6movI','Rodrigo Zin - Hora de Aventura','nkh02_6movI',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','hora','aventura'],NULL,NULL,NULL,true),
('rodrigozin-RVdRO5Pz62s','Rodrigo Zin - Sasuke Uchiha','RVdRO5Pz62s',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','sasuke','uchiha'],NULL,NULL,NULL,true),
('rodrigozin-3e-JTPV1xos','Rodrigo Zin - Tanjiro Kamado','3e-JTPV1xos',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','tanjiro','kamado'],NULL,NULL,NULL,true),
('rodrigozin-au9d6l_fy3Y','Rodrigo Zin - Inosuke Hashibira (Part. Enygma)','au9d6l_fy3Y',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','inosuke','hashibira','part','enygma'],NULL,NULL,NULL,true),
('rodrigozin-s5_FvhIo6v8','Rodrigo Zin - Billy Butcher','s5_FvhIo6v8',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','billy','butcher'],NULL,NULL,NULL,true),
('rodrigozin-v8dNsNPyVbc','Rodrigo Zin - Sengoku','v8dNsNPyVbc',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','sengoku'],NULL,NULL,NULL,true),
('rodrigozin-8NqrwyzoaGw','Rodrigo Zin - Shanks Figarland','8NqrwyzoaGw',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','shanks','figarland'],NULL,NULL,NULL,true),
('rodrigozin-rnrSjXfKfTE','Rodrigo Zin - Smoker','rnrSjXfKfTE',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','smoker'],NULL,NULL,NULL,true),
('rodrigozin-PLvS9x56Z7k','Rodrigo Zin - Buggy','PLvS9x56Z7k',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','buggy'],NULL,NULL,NULL,true),
('rodrigozin-ZiO5lIbfaFM','Rodrigo Zin & Ardlez - Victor Morningstar & Nathaly Willians','ZiO5lIbfaFM',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','ardlez','victor','morningstar','nathaly','willians'],NULL,NULL,NULL,true),
('rodrigozin-SIqlmV7D_LI','Rodrigo Zin - Donquixote Doflamingo','SIqlmV7D_LI',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','donquixote','doflamingo'],NULL,NULL,NULL,true),
('rodrigozin-xFoVrSGAG1A','Rodrigo Zin - Jinbe (Part. Anny)','xFoVrSGAG1A',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','jinbe','part','anny'],NULL,NULL,NULL,true),
('rodrigozin-FGGtFJ_8YgM','Rodrigo Zin - Chihiro Rokuhira (Kagurabachi)','FGGtFJ_8YgM',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','chihiro','rokuhira','kagurabachi'],NULL,NULL,NULL,true),
('rodrigozin-BL2VsIXyHZM','Rodrigo Zin - Aki Hayakawa (Chainsaw Man)','BL2VsIXyHZM',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','aki','hayakawa','chainsaw','man'],NULL,NULL,NULL,true),
('rodrigozin-yhCFDL_Kzvg','Rodrigo Zin - Sengoku (Remix) [ESPECIAL 200K]','yhCFDL_Kzvg',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','sengoku','remix','especial','200k'],NULL,NULL,NULL,true),
('rodrigozin-BCRZyN-mF3E','Rodrigo Zin - Ekko (Arcane)','BCRZyN-mF3E',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','ekko','arcane'],NULL,NULL,NULL,true),
('rodrigozin-ssZmd156Y-M','Rodrigo Zin - Attack on Titan [PUBG Mobile x AoT]','ssZmd156Y-M',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','attack','titan','pubg','mobile','aot'],NULL,NULL,NULL,true),
('rodrigozin-0Vb-B42ijFU','Rodrigo Zin - Haikyū!! FLYHIGH (Part. @DublandoCoisas & @Matosu )','0Vb-B42ijFU',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','haikyu','flyhigh','part','dublandocoisas','matosu'],NULL,NULL,NULL,true),
('rodrigozin-lbkE9zs5uEM','Rodrigo Zin - Hornet (EP) 🧵','lbkE9zs5uEM',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','hornet'],NULL,NULL,NULL,true),
('rodrigozin-tv58tZheoOU','01. Rodrigo Zin - Hallownest (Hollow Knight)','tv58tZheoOU',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','hallownest','hollow','knight'],NULL,NULL,NULL,true),
('rodrigozin-1yDwsWrwVE0','02. Rodrigo Zin - Pharloom (Hollow Knight Silksong) [Part. Taka & Raphyx]','1yDwsWrwVE0',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','pharloom','hollow','knight','silksong','part','taka','raphyx'],NULL,NULL,NULL,true),
('rodrigozin-48TGbMhyaIk','03. Rodrigo Zin - Primeiro Ato (Hollow Knight Silksong)','48TGbMhyaIk',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','primeiro','ato','hollow','knight','silksong'],NULL,NULL,NULL,true),
('rodrigozin-d3rOsV1gBrk','04. Rodrigo Zin & Raphyx - Renitente (Remix)','d3rOsV1gBrk',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','raphyx','renitente','remix'],NULL,NULL,NULL,true),
('rodrigozin-Jx3blhSRpoc','05. Rodrigo Zin - Segundo Ato','Jx3blhSRpoc',0,'GEEKS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','segundo','ato'],NULL,NULL,NULL,true),
('rodrigozin-lKO03HTu4UE','01 Rodrigo Zin - Invasor (Part. Luiza Guimarães & Maina Suzuki)','lKO03HTu4UE',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','invasor','part','luiza','guimaraes','maina','suzuki'],NULL,NULL,NULL,true),
('rodrigozin-DMSmfBJLEnc','02 Rodrigo Zin - Não Acreditei','DMSmfBJLEnc',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','nao','acreditei'],NULL,NULL,NULL,true),
('rodrigozin-R-iqeUZusmA','03 Rodrigo Zin - Viagem de Chihiro','R-iqeUZusmA',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','viagem','chihiro'],NULL,NULL,NULL,true),
('rodrigozin--1EIx32hHC8','04 Rodrigo Zin - Roda Gigante','-1EIx32hHC8',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','roda','gigante'],NULL,NULL,NULL,true),
('rodrigozin-D-v74OaX-iQ','05 Rodrigo Zin - Sem Querer','D-v74OaX-iQ',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','sem','querer'],NULL,NULL,NULL,true),
('rodrigozin-YqoyesTtdvc','06 Rodrigo Zin - Algodão Interlúdio (Part. 1LUM3 & Chefe TF)','YqoyesTtdvc',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','algodao','interludio','part','1lum3','chefe'],NULL,NULL,NULL,true),
('rodrigozin-Vgua5ee_mtg','07 Rodrigo Zin - Reigan (Part. adieu)','Vgua5ee_mtg',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','reigan','part','adieu'],NULL,NULL,NULL,true),
('rodrigozin-HNOHmMapn1M','08 Rodrigo Zin - Desabafos Não Mentem (Part. Lucas Silveira)','HNOHmMapn1M',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','desabafos','nao','mentem','part','lucas','silveira'],NULL,NULL,NULL,true),
('rodrigozin-hq8Iady_TKY','09 Rodrigo Zin - Camomila','hq8Iady_TKY',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','camomila'],NULL,NULL,NULL,true),
('rodrigozin-dWlwqkE3YGA','Rodrigo Zin - Invasor (Álbum Completo)','dWlwqkE3YGA',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','invasor','album','completo'],NULL,NULL,NULL,true),
('rodrigozin-5g2rO_OldNA','01 - Rodrigo Zin - O Mais Vendido','5g2rO_OldNA',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','mais','vendido'],NULL,NULL,NULL,true),
('rodrigozin-mqHNDJn6EMY','02 - Rodrigo Zin - Menos Que Viver','mqHNDJn6EMY',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','menos','que','viver'],NULL,NULL,NULL,true),
('rodrigozin--OYDpeK15GA','03 - Rodrigo Zin - Imaterial (Part. GEO)','-OYDpeK15GA',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','imaterial','part','geo'],NULL,NULL,NULL,true),
('rodrigozin-HxNj4dkacyg','04 - Rodrigo Zin - Remendos','HxNj4dkacyg',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','remendos'],NULL,NULL,NULL,true),
('rodrigozin-VNb9T2IGwBw','05 - Rodrigo Zin - Fazendo Grana Pro Meu Filme','VNb9T2IGwBw',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','fazendo','grana','pro','meu','filme'],NULL,NULL,NULL,true),
('rodrigozin-4ne42-JvsfU','06 - Rodrigo Zin - Jujuba','4ne42-JvsfU',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','jujuba'],NULL,NULL,NULL,true),
('rodrigozin-I09i_aLyWWw','07 - Rodrigo Zin - Anti-Inflamatório','I09i_aLyWWw',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','anti','inflamatorio'],NULL,NULL,NULL,true),
('rodrigozin-aSkcsl_WeBE','08 - Rodrigo Zin - Peças Quebradas de um Teatro Esquecido','aSkcsl_WeBE',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','pecas','quebradas','teatro','esquecido'],NULL,NULL,NULL,true),
('rodrigozin-cGkTZmlSkaA','09 - Rodrigo Zin - Atreus (Part. Lucas A.R.T)','cGkTZmlSkaA',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','atreus','part','lucas'],NULL,NULL,NULL,true),
('rodrigozin-dx4Up-njK_I','10 - Rodrigo Zin - Comprei Você (Part. 1LUM3)','dx4Up-njK_I',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','comprei','voce','part','1lum3'],NULL,NULL,NULL,true),
('rodrigozin-jIsahTxSFDE','11 - Rodrigo Zin - Grana Gama II (Part. Ju Maia e Nebula)','jIsahTxSFDE',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','grana','gama','part','maia','nebula'],NULL,NULL,NULL,true),
('rodrigozin-OA03l6K_4PE','Rodrigo Zin - O Mais Vendido (Clipe Oficial)','OA03l6K_4PE',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['rodrigo','zin','mais','vendido','clipe','oficial'],NULL,NULL,NULL,true),
('rodrigozin-Jxk1RQhcRag','Todos os Samples de ','Jxk1RQhcRag',0,'AUTORAIS','RODRIGOZIN',NULL,ARRAY['todos','samples','fazendo','grana','pro','meu','filme','rodrigo','zin'],NULL,NULL,NULL,true),
('mitski-9ffnue9zMEY','Mitski - A Burning Hill','9ffnue9zMEY',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-wWHsr3VQadc','Mitski - A Horse Named Cold Air','wWHsr3VQadc',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-GIdawcrXlPo','Mitski - A Loving Feeling','GIdawcrXlPo',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-p8FDl_tMs4Y','Mitski - A Pearl','p8FDl_tMs4Y',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-uf0rzDVijC0','Mitski - Bag of Bones','uf0rzDVijC0',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-MpAQJYh3ljI','Mitski - Because Dreaming Costs Money, My Dear','MpAQJYh3ljI',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-TpXNon9QKXY','Mitski - Blue Light','TpXNon9QKXY',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-zgI56IFtQto','Mitski - Brand New City','zgI56IFtQto',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-NafP0MbGEuE','Mitski - Buffalo Replaced','NafP0MbGEuE',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-5WW7cuAm-7Y','Mitski - Bug Like an Angel','5WW7cuAm-7Y',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-ZgJcmeqZFnM','Mitski - Carry Me Out','ZgJcmeqZFnM',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-0gHWLbgSUbI','Mitski - Circle','0gHWLbgSUbI',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-4y0O7gAQEFU','Mitski - Class of 2013','4y0O7gAQEFU',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-22yRUQMjvUA','Mitski - Come Into the Water','22yRUQMjvUA',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-aIaqTsCcWsw','Mitski - Crack Baby','aIaqTsCcWsw',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-8jMUQKpsbhk','Mitski - Dan the Dancer','8jMUQKpsbhk',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-TijrUpgClyQ','Mitski - Door','TijrUpgClyQ',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-38_WVr5H2FA','Mitski - Drunk Walk Home','38_WVr5H2FA',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-kRPI6JSCOK0','Mitski - Eric','kRPI6JSCOK0',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-AyXm7ZZRJjM','Mitski - Everyone','AyXm7ZZRJjM',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-rVRMh2PVE80','Mitski - Fireworks','rVRMh2PVE80',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-DVIaDzs1EH4','Mitski - First Love/Late Spring','DVIaDzs1EH4',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-mHKTdlUyyko','Mitski - Francis Forever','mHKTdlUyyko',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-3zdFZJf-B90','Mitski - Geyser','3zdFZJf-B90',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-ohxu-pA7o64','Mitski - Goodbye, My Danish Sweetheart','ohxu-pA7o64',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-gvIkcN5YMH4','Mitski - Heat Lightning','gvIkcN5YMH4',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true),
('mitski-dJ9O_2l5ln0','Mitski - Humpty','dJ9O_2l5ln0',0,'POP','MITSKI',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;