INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('tanjiro','Rap do Tanjiro (Demon Slayer) - Filho do Sol','pUCOziorxHw',0,'NERD HITS','7MZ','Demon Slayer',ARRAY['tanjiro','demon slayer','kimetsu','sol'],NULL,NULL,NULL,true),
('luffy-rei','Rap do Luffy (One Piece) - Rei dos Piratas','hgTuSp_qF0Q',0,'NERD HITS','7MZ','One Piece',ARRAY['luffy','one piece','rei','piratas'],NULL,NULL,NULL,true),
('asta-rei-mago','Rap do Asta (Black Clover) - Eu Vou Ser o Rei Mago','QDLVSyBQHDU',0,'NERD HITS','7MZ','Black Clover',ARRAY['asta','black clover','rei mago'],NULL,NULL,NULL,true),
('near-mello','Rap do Near e Mello (Death Note) - O Sucessor do L','0fip0Jce2nU',0,'NERD HITS','7MZ','Death Note',ARRAY['near','mello','death note','sucessor'],NULL,NULL,NULL,true),
('l-death-note','Rap do L (Death Note) - O Maior Detetive','fCtWj7X31jE',0,'NERD HITS','7MZ','Death Note',ARRAY['l','death note','detetive','lawliet'],NULL,NULL,NULL,true),
('kira','Rap do Kira (Death Note) - O Deus do Novo Mundo','cJA8371FeOA',0,'NERD HITS','7MZ','Death Note',ARRAY['kira','light','death note','deus','yagami'],NULL,NULL,NULL,true),
('time-7','Rap do Kakashi, Naruto, Sasuke e Sakura - Time 7','SkdtL4OPzB0',0,'NERD HITS','7MZ','Naruto',ARRAY['kakashi','naruto','sasuke','sakura','time 7'],NULL,NULL,NULL,true),
('cavaleiros-zodiaco','Rap dos Cavaleiros do Zodíaco - Por Atena','5d2HD3AugAo',0,'NERD HITS','7MZ','Cavaleiros do Zodíaco',ARRAY['cavaleiros','zodíaco','atena','saint seiya'],NULL,NULL,NULL,true),
('momentos-quem-se-foi-2','Rap do Capitão América, Thor e Gavião Arqueiro - Momentos com Quem Se Foi 2','lEqa9F-yg4k',0,'NERD HITS','7MZ','Marvel',ARRAY['capitão américa','thor','gavião','momentos'],NULL,NULL,NULL,true),
('cruel-2','Rap do Freeza, Cell e Majin Boo - O Quanto Eu Posso Ser Cruel 2','P4SNlVBMGH8',0,'NERD HITS','7MZ','Dragon Ball Z',ARRAY['freeza','cell','majin boo','cruel'],NULL,NULL,NULL,true),
('destruidor-mundos','Rap da Kaguya, Bills e Galactus - Destruidor de Mundos','cj2gAo1FruE',0,'NERD HITS','7MZ',NULL,ARRAY['kaguya','bills','galactus','destruidor'],NULL,NULL,NULL,true),
('majin-boo','Rap do Majin Boo (Dragon Ball Z) - Eu Sou um Caos','6gl9NGD01eI',0,'NERD HITS','7MZ','Dragon Ball Z',ARRAY['majin boo','dragon ball','caos'],NULL,NULL,NULL,true),
('jiren','Rap do Jiren (Dragon Ball Super) - Mais Forte que uma Divindade','6QdRop70Sbo',0,'NERD HITS','7MZ','Dragon Ball Super',ARRAY['jiren','dragon ball','divindade'],NULL,NULL,NULL,true),
('thanos-ultimato','Rap do Thanos (Vingadores: Ultimato) - Eu Sou Inevitável','EiGeQ2dVdh8',0,'NERD HITS','7MZ','Vingadores: Ultimato',ARRAY['thanos','vingadores','ultimato','inevitável'],NULL,NULL,NULL,true),
('shikamaru','Rap do Shikamaru (Naruto) - Cuidado com as Sombras','J52kqPXw4e0',0,'NERD HITS','7MZ','Naruto',ARRAY['shikamaru','naruto','sombras','nara'],NULL,NULL,NULL,true),
('kakashi-obito-rin','Rap do Kakashi, Obito e Rin (Naruto) - Ninjas Merecem Perdão','SAhdAyMMB3o',0,'NERD HITS','7MZ','Naruto',ARRAY['kakashi','obito','rin','naruto','perdão'],NULL,NULL,NULL,true),
('akatsuki','Rap da Akatsuki (Naruto) - Os Ninjas Mais Procurados do Mundo','-oYMo8k22Vw',0,'NERD HITS','7MZ','Naruto',ARRAY['akatsuki','naruto','ninjas','procurados'],NULL,NULL,NULL,true),
('deidara','Rap do Deidara (Naruto) - A Arte É a Explosão','y2LqIojs2wc',0,'NERD HITS','7MZ','Naruto',ARRAY['deidara','naruto','arte','explosão','akatsuki'],NULL,NULL,NULL,true),
('naruto-setimo','Rap do Naruto - O Sétimo Hokage','ObQMysW58NA',0,'NERD HITS','7MZ','Naruto',ARRAY['naruto','sétimo','hokage'],NULL,NULL,NULL,true),
('doutor-estranho','Rap do Doutor Estranho - Mago Supremo do Universo','AW7JllAXiBc',0,'NERD HITS','7MZ','Marvel',ARRAY['doutor estranho','mago','supremo','strange'],NULL,NULL,NULL,true),
('deadpool','Rap do Deadpool - O Mercenário Tagarela','ZjEjCSvozHU',0,'NERD HITS','7MZ','Marvel',ARRAY['deadpool','mercenário','tagarela'],NULL,NULL,NULL,true),
('saitama-mais-forte','Rap do Saitama (One Punch Man) - O Homem Mais Forte','NlQpa0ifFy8',0,'NERD HITS','7MZ','One Punch Man',ARRAY['saitama','one punch man','mais forte'],NULL,NULL,NULL,true),
('goku-deus','Rap do Goku (Dragon Ball Super) - Deus Super Saiyajin','SoEp7GCsNvc',0,'NERD HITS','7MZ','Dragon Ball Super',ARRAY['goku','dragon ball','deus','saiyajin'],NULL,NULL,NULL,true),
('gaara-caixao','Rap do Gaara (Naruto) - Caixão de Areia','56oSoyN-kTY',0,'NERD HITS','7MZ','Naruto',ARRAY['gaara','naruto','caixão','areia'],NULL,NULL,NULL,true),
('coringas','Rap dos Coringas - Circo dos Horrores','qMNX3FJh4Z4',0,'NERD HITS','7MZ','DC Comics',ARRAY['coringas','circo','horrores','coringa','joker'],NULL,NULL,NULL,true),
('superman','Rap do Superman - Homem de Aço','M7Ood7SL5UI',0,'NERD HITS','7MZ','DC Comics',ARRAY['superman','homem de aço'],NULL,NULL,NULL,true),
('batman-trevas','Rap do Batman - Cavaleiro das Trevas','cqXV6jYhlFY',0,'NERD HITS','7MZ','DC Comics',ARRAY['batman','cavaleiro','trevas'],NULL,NULL,NULL,true),
('flash','Rap do Flash - O Homem Mais Rápido do Mundo','tKtV1InzvWM',0,'NERD HITS','7MZ','DC Comics',ARRAY['flash','rápido','velocidade'],NULL,NULL,NULL,true),
('aquaman','Rap do Aquaman - O Rei do Mar','ce4EP8tj5es',0,'NERD HITS','7MZ','DC Comics',ARRAY['aquaman','rei','mar'],NULL,NULL,NULL,true),
('animal','Rap do Gaara, Venom e Wolverine - Animal','3v9lztbA5kM',0,'NERD HITS','7MZ','Marvel',ARRAY['gaara','venom','wolverine','animal'],NULL,NULL,NULL,true),
('aranha-longe-casa','Rap do Homem-Aranha (Longe de Casa) - Eu Te Amo Mil Milhões','ZrYLl_NbUFM',0,'NERD HITS','7MZ','Longe de Casa',ARRAY['homem-aranha','longe de casa','mil milhões'],NULL,NULL,NULL,true),
('cap-ultimato','Rap do Capitão América (Vingadores: Ultimato) - Eu Vou Me Vingar','bQhpa6hYxQU',0,'NERD HITS','7MZ','Vingadores: Ultimato',ARRAY['capitão américa','vingadores','ultimato','vingar'],NULL,NULL,NULL,true),
('thor-ultimato','Rap do Thor (Vingadores: Ultimato) - Eu Ainda Sou Digno','zWM4qq3MzFE',0,'NERD HITS','7MZ','Vingadores: Ultimato',ARRAY['thor','vingadores','ultimato','digno'],NULL,NULL,NULL,true),
('iron-man-ultimato','Rap do Homem de Ferro (Vingadores: Ultimato) - Eu Sou o Homem de Ferro','R-9hB553mz4',0,'NERD HITS','7MZ','Vingadores: Ultimato',ARRAY['homem de ferro','iron man','vingadores','ultimato'],NULL,NULL,NULL,true),
('luffy-natsu-ichigo','Rap do Luffy, Natsu e Ichigo - É Isso Que Me Faz um Herói','KjmEh-S2Rw0',0,'NERD HITS','7MZ',NULL,ARRAY['luffy','natsu','ichigo','herói'],NULL,NULL,NULL,true),
('midoriya','Rap do Midoriya (Boku no Hero) - Eu Sempre Fui um Herói','1lxX51Awaic',0,'NERD HITS','7MZ','Boku no Hero Academia',ARRAY['midoriya','deku','boku no hero','herói'],NULL,NULL,NULL,true),
('chucky','Rap do Chucky (Brinquedo Assassino) - Vou Brincar Com Você','Cdi1ycawK6c',0,'NERD HITS','7MZ','Brinquedo Assassino',ARRAY['chucky','brinquedo assassino','brincar'],NULL,NULL,NULL,true),
('jeff-killer','Rap do Jeff The Killer (Creepypasta) - O Jeff Chegou','6hmPOWq8SLg',0,'NERD HITS','7MZ','Creepypasta',ARRAY['jeff','killer','creepypasta'],NULL,NULL,NULL,true),
('freddy-krueger','Rap do Freddy Krueger (Hora do Pesadelo) - O Senhor dos Pesadelos','Gu0lKn1xFQw',0,'NERD HITS','7MZ','Hora do Pesadelo',ARRAY['freddy','krueger','pesadelo'],NULL,NULL,NULL,true),
('jason','Rap do Jason (Sexta-Feira 13) - A Noite de Caça Começou','Z_8PUABBX5c',0,'NERD HITS','7MZ','Sexta-Feira 13',ARRAY['jason','sexta-feira 13','caça'],NULL,NULL,NULL,true),
('shisui','Rap do Shisui (Naruto) - Meu Sacrifício','dET5ZzBSJv8',0,'NERD HITS','7MZ','Naruto',ARRAY['shisui','naruto','sacrifício','uchiha'],NULL,NULL,NULL,true),
('tsunade','Rap da Tsunade (Naruto) - Quinta Hokage','XGUt6klmgp4',0,'NERD HITS','7MZ','Naruto',ARRAY['tsunade','naruto','quinta','hokage'],NULL,NULL,NULL,true),
('hashirama','Rap do Hashirama (Naruto) - O Primeiro Hokage','S8iYNNpKvCw',0,'NERD HITS','7MZ','Naruto',ARRAY['hashirama','naruto','primeiro','hokage','senju'],NULL,NULL,NULL,true),
('madara','Rap do Madara (Naruto) - Me Tornei um Deus','fMut2esOT5w',0,'NERD HITS','7MZ','Naruto',ARRAY['madara','naruto','deus','uchiha'],NULL,NULL,NULL,true),
('obito','Rap do Obito (Naruto) - Mais Ninguém Vai Sofrer o Que Eu Sofri','1mwTKq_6tCo',0,'NERD HITS','7MZ','Naruto',ARRAY['obito','naruto','sofrer','uchiha','tobi'],NULL,NULL,NULL,true),
('vegeta','Rap do Vegeta (Dragon Ball Z) - Pura Maldade','yDj-2M08Ky0',0,'NERD HITS','7MZ','Dragon Ball Z',ARRAY['vegeta','dragon ball','maldade','príncipe','saiyajin'],NULL,NULL,NULL,true),
('kratos','Rap do Kratos (God of War) - Eu Sou um Deus','y0z5OIatnyE',0,'NERD HITS','7MZ','God of War',ARRAY['kratos','god of war','deus'],NULL,NULL,NULL,true),
('meliodas-ban-escanor','Rap do Meliodas, Ban e Escanor (Nanatsu no Taizai) - O Pecado Mais Forte','yQh6NTeKEFo',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['meliodas','ban','escanor','nanatsu','pecado'],NULL,NULL,NULL,true),
('diane','Rap da Diane (Nanatsu no Taizai) - O Pecado da Inveja','eW-lAKG6X_s',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['diane','nanatsu','inveja','pecado'],NULL,NULL,NULL,true),
('gowther','Rap do Gowther (Nanatsu no Taizai) - Eu Não Tenho Coração','r0uzxJrkUz4',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['gowther','nanatsu','coração','pecado'],NULL,NULL,NULL,true),
('zeldris','Rap do Zeldris (Nanatsu no Taizai) - O Mandamento da Piedade','kF39d4n-j-c',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['zeldris','nanatsu','mandamento','piedade'],NULL,NULL,NULL,true),
('vingadores-ultimato','Rap dos Vingadores: Ultimato - Custe o Que Custar','eePyfPp1Y9U',0,'NERD HITS','7MZ','Marvel',ARRAY['vingadores','ultimato','custe'],NULL,NULL,NULL,true),
('sasuke-maldicao','Rap do Sasuke (Naruto) - Maldição do Ódio','WYJ2hKTXKWA',0,'NERD HITS','7MZ','Naruto',ARRAY['sasuke','naruto','maldição','ódio','uchiha'],NULL,NULL,NULL,true),
('estarossa','Rap do Estarossa (Nanatsu no Taizai) - O Mandamento do Amor','h7rWDisgvK0',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['estarossa','nanatsu','mandamento','amor'],NULL,NULL,NULL,true),
('hulk','Rap do Hulk - Tô Sempre com Raiva','HyqqCuBtpvA',0,'NERD HITS','7MZ','Marvel',ARRAY['hulk','raiva','bruce banner'],NULL,NULL,NULL,true),
('iron-man','Rap do Homem de Ferro - I Am Iron Man','g6xTDPc6Hh0',0,'NERD HITS','7MZ','Marvel',ARRAY['homem de ferro','iron man','tony stark'],NULL,NULL,NULL,true),
('broly','Rap do Broly (Dragon Ball Z) - Lendário Super Saiyajin','vOCzCfPH5EQ',0,'NERD HITS','7MZ','Dragon Ball Z',ARRAY['broly','dragon ball','lendário','saiyajin'],NULL,NULL,NULL,true),
('cap-america','Rap do Capitão América - O Primeiro Vingador','DWZwIMZmPNs',0,'NERD HITS','7MZ','Marvel',ARRAY['capitão américa','primeiro vingador','steve rogers'],NULL,NULL,NULL,true),
('thanos','Rap do Thanos (Vingadores) - O Thanos Está Vindo','1kwPr91Vs-A',0,'NERD HITS','7MZ','Vingadores',ARRAY['thanos','vingadores','vindo'],NULL,NULL,NULL,true),
('orochimaru','Rap do Orochimaru (Naruto) - Eu Vou Viver pra Sempre','kKoH-dKLIjU',0,'NERD HITS','7MZ','Naruto',ARRAY['orochimaru','naruto','viver','sempre'],NULL,NULL,NULL,true),
('pain-shinra','Rap do Nagato / Pain (Naruto) - Shinra Tensei','KN4Tnp6XcGk',0,'NERD HITS','7MZ','Naruto',ARRAY['pain','nagato','shinra tensei','naruto'],NULL,NULL,NULL,true),
('jiraiya','Rap do Jiraiya (Naruto) - O Conto de um Ninja Destemido','pdaSjP9DwXs',0,'NERD HITS','7MZ','Naruto',ARRAY['jiraiya','naruto','ninja','destemido','ero-sennin'],NULL,NULL,NULL,true),
('trunks-futuro','Rap do Trunks do Futuro (Dragon Ball Z) - O Último Saiyajin','5bCXfF_IYlU',0,'NERD HITS','7MZ','Dragon Ball Z',ARRAY['trunks','futuro','dragon ball','último','saiyajin'],NULL,NULL,NULL,true),
('gamora','Rap da Gamora (Guardiões da Galáxia) - A Mulher Mais Temida da Galáxia','d7d6_spCs_A',0,'NERD HITS','7MZ','Guardiões da Galáxia',ARRAY['gamora','guardiões','galáxia'],NULL,NULL,NULL,true),
('homem-formiga','Rap do Homem-Formiga - Soldado Microscópico','BNakihwBX_M',0,'NERD HITS','7MZ','Marvel',ARRAY['homem-formiga','ant-man','microscópico'],NULL,NULL,NULL,true),
('loki','Rap do Loki (Thor) - O Deus da Mentira','NiLIKstxk7U',0,'NERD HITS','7MZ','Thor',ARRAY['loki','thor','deus','mentira'],NULL,NULL,NULL,true),
('thor','Rap do Thor - A Ira de um Deus','s0-gIEq5exs',0,'NERD HITS','7MZ','Marvel',ARRAY['thor','ira','deus','mjolnir'],NULL,NULL,NULL,true),
('rock-lee','Rap do Rock Lee (Naruto) - A Força da Motivação','XwAzVXBjvNo',0,'NERD HITS','7MZ','Naruto',ARRAY['rock lee','naruto','motivação','taijutsu'],NULL,NULL,NULL,true),
('hinata','Rap da Hinata (Naruto) - Se For por Você...','eWZ4V4IGcb4',0,'NERD HITS','7MZ','Naruto',ARRAY['hinata','naruto','hyuuga'],NULL,NULL,NULL,true),
('neji','Rap do Neji (Naruto) - O Preço da Liberdade','pQ5rO4dp3TQ',0,'NERD HITS','7MZ','Naruto',ARRAY['neji','naruto','liberdade','hyuuga'],NULL,NULL,NULL,true),
('maito-gai','Rap do Maito Gai (Naruto) - O Ninja Mais Forte','i_NDEiPtnp8',0,'NERD HITS','7MZ','Naruto',ARRAY['gai','maito','naruto','ninja','forte'],NULL,NULL,NULL,true),
('batman-gotham','Rap do Batman - Cavaleiro de Gotham','PBmZknvybo8',0,'NERD HITS','7MZ','DC Comics',ARRAY['batman','gotham','cavaleiro'],NULL,NULL,NULL,true),
('goku-black','Rap do Goku Black (Dragon Ball Super) - Eu Sou a Justiça','gsW9IvgrR7s',0,'NERD HITS','7MZ','Dragon Ball Super',ARRAY['goku black','dragon ball','justiça','zamasu'],NULL,NULL,NULL,true),
('freeza','Rap do Freeza (Dragon Ball Super) - Imperador do Universo','9LPhHsjOm7U',0,'NERD HITS','7MZ','Dragon Ball Super',ARRAY['freeza','dragon ball','imperador','universo'],NULL,NULL,NULL,true),
('poder-ira','Rap do Kratos, Meliodas e Naruto - O Poder da Minha Ira','TnFG3olJwHA',0,'NERD HITS','7MZ','God of War',ARRAY['kratos','meliodas','naruto','poder','ira'],NULL,NULL,NULL,true),
('desculpe-partir','Rap do Minato, Neji e Jiraiya (Naruto) - Me Desculpe por Partir...','WZR1CE4o_uE',0,'NERD HITS','7MZ','Naruto',ARRAY['minato','neji','jiraiya','naruto','desculpe','partir'],NULL,NULL,NULL,true),
('coringa-batman','Rap do Coringa (Batman) - Por Que Está Tão Sério?','9qhhY-YKLp0',0,'NERD HITS','7MZ','Batman',ARRAY['coringa','batman','sério','joker'],NULL,NULL,NULL,true),
('eren','Rap do Eren (Attack on Titan) - A Fúria de um Titã','dMKTONbHRtg',0,'NERD HITS','7MZ','Attack on Titan',ARRAY['eren','attack on titan','titã','fúria','shingeki'],NULL,NULL,NULL,true),
('levi','Rap do Capitão Levi (Attack on Titan) - O Mais Forte da Humanidade','-cihN-wmo30',0,'NERD HITS','7MZ','Attack on Titan',ARRAY['levi','attack on titan','forte','humanidade','ackerman'],NULL,NULL,NULL,true),
('venom','Rap do Venom (Homem-Aranha) - Nós Somos Venom','QK6IWDm6vuQ',0,'NERD HITS','7MZ','Homem-Aranha',ARRAY['venom','homem-aranha','simbionte'],NULL,NULL,NULL,true),
('aranha-lar','Rap do Homem-Aranha - Eu Tô de Volta ao Lar','nFrfrU5C4Eo',0,'NERD HITS','7MZ','Marvel',ARRAY['homem-aranha','volta','lar','peter parker'],NULL,NULL,NULL,true),
('gaara-monstro','Rap do Gaara (Naruto) - Acho Que Eu Sou um Monstro...','KWqngXyY6_w',0,'NERD HITS','7MZ','Naruto',ARRAY['gaara','naruto','monstro'],NULL,NULL,NULL,true),
('minato','Rap do Minato (Naruto) - O Dever de um Pai','ZHinw8orxM4',0,'NERD HITS','7MZ','Naruto',ARRAY['minato','naruto','pai','namikaze'],NULL,NULL,NULL,true),
('todoroki-2','Rap do Todoroki (Boku no Hero) - Obrigado por Me Libertar','41uuesH-sAc',0,'NERD HITS','7MZ','Boku no Hero Academia',ARRAY['todoroki','boku no hero','libertar'],NULL,NULL,NULL,true),
('all-might','Rap do All Might (Boku no Hero) - O Símbolo da Paz','JhYqNZNGLMM',0,'NERD HITS','7MZ','Boku no Hero Academia',ARRAY['all might','boku no hero','símbolo','paz'],NULL,NULL,NULL,true),
('kakashi','Rap do Kakashi (Naruto) - Aquele Que Copia os 1.000 Jutsus','b4K1P8uQOcM',0,'NERD HITS','7MZ','Naruto',ARRAY['kakashi','naruto','copia','jutsus','hatake'],NULL,NULL,NULL,true),
('itachi','Rap do Itachi (Naruto) - Essa Dor Que Causei...','zs_zpMnwNMs',0,'NERD HITS','7MZ','Naruto',ARRAY['itachi','naruto','dor','uchiha'],NULL,NULL,NULL,true),
('king','Rap do King (Nanatsu no Taizai) - Rei das Fadas','-U8OdHA8elo',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['king','nanatsu','fadas','harlequin'],NULL,NULL,NULL,true),
('escanor','Rap do Escanor (Nanatsu no Taizai) - Orgulhoso Como um Leão','xAftKacljfo',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['escanor','nanatsu','leão','orgulhoso','pecado'],NULL,NULL,NULL,true),
('slender-man','Rap do Slender Man - O Homem Sem Face','2AGZ3CfwNwc',0,'NERD HITS','7MZ','Creepypasta',ARRAY['slender man','sem face'],NULL,NULL,NULL,true),
('pennywise','Rap do Pennywise (IT: A Coisa) - O Palhaço','UFDdhqQ3WE0',0,'NERD HITS','7MZ','IT: A Coisa',ARRAY['pennywise','it','palhaço','coisa'],NULL,NULL,NULL,true),
('cruel','Rap do Madara, Pain e Orochimaru - O Quanto Eu Posso Ser Cruel','11vD3MUpOkM',0,'NERD HITS','7MZ','Naruto',ARRAY['madara','pain','orochimaru','cruel'],NULL,NULL,NULL,true),
('momentos-quem-se-foi','Rap do Homem-Aranha, Flash e Batman - Momentos com Quem Se Foi...','sMhWUp3OQ00',0,'NERD HITS','7MZ','DC Comics',ARRAY['homem-aranha','flash','batman','momentos'],NULL,NULL,NULL,true),
('ban','Rap do Ban (Nanatsu no Taizai) - O Pecado da Ganância','dUoWRyZiVaA',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['ban','nanatsu','ganância','pecado'],NULL,NULL,NULL,true),
('meliodas','Rap do Meliodas (Nanatsu no Taizai) - Eu Sou o Capitão','4A-2AmQ7Lvg',0,'NERD HITS','7MZ','Nanatsu no Taizai',ARRAY['meliodas','nanatsu','capitão'],NULL,NULL,NULL,true),
('vingadores-guerra','Rap dos Vingadores: Guerra Infinita - Em Guerra pra Sempre','8Ip_0POXqdA',0,'NERD HITS','7MZ','Marvel',ARRAY['vingadores','guerra infinita','guerra'],NULL,NULL,NULL,true),
('midoriya-2','Rap do Midoriya (Boku no Hero) - Eu Tenho Que Acreditar','f3pfiUgL-PU',0,'NERD HITS','7MZ','Boku no Hero Academia',ARRAY['midoriya','deku','boku no hero','acreditar'],NULL,NULL,NULL,true),
('saitama','Rap do Saitama (One Punch Man) - Um Só','vtZPJ1X91fM',0,'NERD HITS','7MZ','One Punch Man',ARRAY['saitama','one punch man','um só'],NULL,NULL,NULL,true),
('sasuke-renegado','Rap do Sasuke - O Renegado','r1blNSgRD00',0,'NERD HITS','7MZ','Naruto',ARRAY['sasuke','renegado','naruto','uchiha'],NULL,NULL,NULL,true),
('naruto-demonio','Rap do Naruto - O Demônio Dentro de Mim','kuhGR_VU3rk',0,'NERD HITS','7MZ','Naruto',ARRAY['naruto','demônio','kurama'],NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;