INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('guardias-estelares','Rap das Guardiãs Estelares (League of Legends) - Garotas Mágicas','edvyy_EYPgs',0,'NERD HITS','7MZ','League of Legends',ARRAY['guardiãs','estelares','league of legends','garotas','mágicas'],NULL,NULL,NULL,true),
('xayah-rakan','Rap da Xayah e Rakan (League of Legends) - Paixão Estelar','zI9N7-mvmj8',0,'NERD HITS','7MZ','League of Legends',ARRAY['xayah','rakan','league of legends','paixão'],NULL,NULL,NULL,true),
('luffy-chapeu','Rap do Luffy (One Piece) - Chapéu de Palha','ivGBhIg-zK4',0,'NERD HITS','7MZ','One Piece',ARRAY['luffy','one piece','chapéu','palha'],NULL,NULL,NULL,true),
('chopper','Rap do Chopper (One Piece) - Sou um Monstro','ZJoHrBYg-iQ',0,'NERD HITS','7MZ','One Piece',ARRAY['chopper','one piece','monstro','tony tony'],NULL,NULL,NULL,true),
('law','Rap do Law (One Piece) - Cirurgião da Morte','HHzIzkPhhaE',0,'NERD HITS','7MZ','One Piece',ARRAY['law','one piece','cirurgião','morte','trafalgar'],NULL,NULL,NULL,true),
('usopp','Rap do Usopp (One Piece) - Um Bravo Guerreiro do Mar','44wn0Huz6DA',0,'NERD HITS','7MZ','One Piece',ARRAY['usopp','one piece','guerreiro','mar'],NULL,NULL,NULL,true),
('crocodile','Rap do Crocodile (One Piece) - O Deserto Será Seu Cemitério','kTl1SWtMvz8',0,'NERD HITS','7MZ','One Piece',ARRAY['crocodile','one piece','deserto','cemitério'],NULL,NULL,NULL,true),
('denji','Rap do Denji (Chainsaw Man) - O Maldito Demônio da Motosserra','Z6AH55TOiQA',0,'NERD HITS','7MZ','Chainsaw Man',ARRAY['denji','chainsaw man','motosserra','demônio'],NULL,NULL,NULL,true),
('kratos-atreus','Rap do Kratos e Atreus (God of War) - Nós Somos Deuses','CFjxhsoR278',0,'NERD HITS','7MZ','God of War',ARRAY['kratos','atreus','god of war','deuses'],NULL,NULL,NULL,true),
('david-martinez','Rap do David Martinez (Cyberpunk: Edgerunners) - Mercenários','qfdcnPdIlCk',0,'NERD HITS','7MZ','Cyberpunk Edgerunners',ARRAY['david','martinez','cyberpunk','edgerunners','mercenários'],NULL,NULL,NULL,true),
('nagato','Rap do Nagato (Naruto) - Minha Dor','iUM3YdqwgPg',0,'NERD HITS','7MZ','Naruto',ARRAY['nagato','naruto','dor','pain'],NULL,NULL,NULL,true),
('zetsu','Rap do Zetsu (Naruto) - Branco e Preto','RPeGVtkSEPU',0,'NERD HITS','7MZ','Naruto',ARRAY['zetsu','naruto','branco','preto','akatsuki'],NULL,NULL,NULL,true),
('sasori','Rap do Sasori (Naruto) - Manipulando Marionetes','Wh9bif_Qm3I',0,'NERD HITS','7MZ','Naruto',ARRAY['sasori','naruto','marionetes','akatsuki'],NULL,NULL,NULL,true),
('eren-estrondo','Eren (Attack on Titan) - Ao Som do Estrondo','cd6HIQ5LY7o',0,'NERD HITS','7MZ','Attack on Titan',ARRAY['eren','attack on titan','estrondo','shingeki'],NULL,NULL,NULL,true),
('zeke','Zeke (Attack on Titan) - Salvação','hWKz75h_Uf8',0,'NERD HITS','7MZ','Attack on Titan',ARRAY['zeke','attack on titan','salvação','yeager'],NULL,NULL,NULL,true),
('armin','Armin (Attack on Titan) - Além das Muralhas','koK9EOEANIc',0,'NERD HITS','7MZ','Attack on Titan',ARRAY['armin','attack on titan','muralhas','arlert'],NULL,NULL,NULL,true),
('capitao-patria','Capitão Pátria (The Boys) - O Que Eu Quiser','MB7_IuMWXlo',0,'NERD HITS','7MZ','The Boys',ARRAY['capitão pátria','the boys','homelander'],NULL,NULL,NULL,true),
('coringa-arlequina','Coringa e Arlequina ft. Amanda Areia e Anny','bq7m7Yzq_2c',0,'NERD HITS','7MZ','DC Comics',ARRAY['coringa','arlequina','amanda','anny'],NULL,NULL,NULL,true),
('vi-jinx','Vi e Jinx','H2JqC7zH2No',0,'NERD HITS','7MZ','League of Legends',ARRAY['vi','jinx','arcane','league of legends'],NULL,NULL,NULL,true),
('mahito','Mahito ft. Small (Novatroop)','ayIn3hFDFYg',0,'NERD HITS','7MZ','Jujutsu Kaisen',ARRAY['mahito','jujutsu kaisen','novatroop','small'],NULL,NULL,NULL,true),
('geto','Suguru Geto ft. Onni','4SANmrgyl8E',0,'NERD HITS','7MZ','Jujutsu Kaisen',ARRAY['geto','suguru','jujutsu kaisen','onni'],NULL,NULL,NULL,true),
('gachiakuta','Rudo Surebrec (Gachiakuta) - Do Paraíso ao Inferno','qeZCx2u_Uz0',0,'NERD HITS','7MZ','Gachiakuta',ARRAY['gachiakuta','rudo','surebrec','paraíso','inferno'],NULL,NULL,NULL,true),
('gohan-furia','Rap do Gohan (Dragon Ball Z) - A FÚRIA DE UM SAIYAJIN | NERD HITS','0QQWwrs39As',0,'NERD HITS','7MZ',NULL,ARRAY['gohan','dragon','ball','furia','saiyajin'],NULL,NULL,NULL,true),
('bills-deus','Rap do Bills (Dragon Ball Super) - DEUS DA DESTRUIÇÃO | NERD HITS','XbUvowjHsAk',0,'NERD HITS','7MZ',NULL,ARRAY['bills','dragon','ball','deus','destruicao'],NULL,NULL,NULL,true),
('goku-vegeta','Rap do Goku e Vegeta (Dragon Ball Super) - O HOMEM MAIS FORTE DO UNIVERSO | NERD HITS','KRXrDOtta10',0,'NERD HITS','7MZ',NULL,ARRAY['goku','vegeta','dragon','ball','homem','forte','universo'],NULL,NULL,NULL,true),
('gato-preto','Gato Preto - Game Over Squad Soundtrack','FEPDoKofKlw',0,'7MZ RECORDS','7MZ','Game Over Squad',ARRAY['gato preto','game over squad'],NULL,NULL,NULL,true),
('deadpool-wolverine','Deadpool e Wolverine - Balas e Garras','6Q8svKIi2N4',0,'7MZ RECORDS','7MZ','Marvel',ARRAY['deadpool','wolverine','balas','garras'],NULL,NULL,NULL,true),
('itadori','Itadori ft. M4rkim','tTAOA8POclQ',0,'7MZ RECORDS','7MZ','Jujutsu Kaisen',ARRAY['itadori','m4rkim','jujutsu kaisen'],NULL,NULL,NULL,true),
('satoru-gojo','Satoru Gojo ft. Henrique Mendonça','fu9dCuPRFHY',0,'7MZ RECORDS','7MZ','Jujutsu Kaisen',ARRAY['gojo','satoru','jujutsu kaisen','henrique'],NULL,NULL,NULL,true),
('radioativo','Radioativo','ICpw2v83Eiw',0,'7MZ RECORDS','7MZ','Original 7MZ',ARRAY['radioativo','lucas art'],NULL,NULL,NULL,true),
('hollow','Hollow','4rti11ZN8d0',0,'7MZ RECORDS','7MZ',NULL,ARRAY['hollow','pedro alvez'],NULL,NULL,NULL,true),
('velha-estrada','Velha Estrada','HFH4z7S4OS4',0,'7MZ RECORDS','7MZ','Original 7MZ',ARRAY['velha estrada'],NULL,NULL,NULL,true),
('asta-lucas','Asta','-dkNV505w5A',0,'7MZ RECORDS','7MZ','Black Clover',ARRAY['asta','lucas art','black clover'],NULL,NULL,NULL,true),
('sukuna','Sukuna ft. Basara','wViRL-63XJk',0,'7MZ RECORDS','7MZ','Jujutsu Kaisen',ARRAY['sukuna','basara','jujutsu kaisen','rei das maldições'],NULL,NULL,NULL,true),
('rei-sangue','Rei do Sangue','riCdGzJrMGk',0,'7MZ RECORDS','7MZ','Original 7MZ',ARRAY['rei','sangue','lucas art'],NULL,NULL,NULL,true),
('avada-kedavra','Avada Kedavra','0rYLz5EjemI',0,'7MZ RECORDS','7MZ',NULL,ARRAY['avada kedavra','harry potter','lucas art'],NULL,NULL,NULL,true),
('ragnarok','Ragnarok','gkkAQM1TPsY',0,'7MZ RECORDS','7MZ',NULL,ARRAY['ragnarok'],NULL,NULL,NULL,true),
('judas','7 Minutoz - JUDAS','6b02hELah9Y',0,'7MZ RECORDS','7MZ',NULL,ARRAY['minutoz','judas'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod','PRA TROPA DE EXPLORAÇÃO - Lucas A.R.T. e Gabriel Rodrigues [Prod. ZZZ Beats]','-3GF-V5_VDU',0,'7MZ RECORDS','7MZ',NULL,ARRAY['pra','tropa','exploracao','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('gabriel-rodrigues-e-lucas','MURALHAS - Gabriel Rodrigues e Lucas A.R.T. [Prod. TRUNXKZ]','n1ZQ8_IQkkQ',0,'7MZ RECORDS','7MZ',NULL,ARRAY['muralhas','gabriel','rodrigues','lucas','a-r-t'],NULL,NULL,NULL,true),
('obito-2','Gabriel Rodrigues - OBITO [Prod. Beck Beatz]','yGcUveAexto',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','obito'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-2','PIRATA - Lucas A.R.T. e Gabriel Rodrigues [Prod. Mxds Beats]','LFIp7iP95eY',0,'7MZ RECORDS','7MZ',NULL,ARRAY['pirata','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('akuma-no-mi','Lucas A.R.T. - AKUMA NO MI [Prod. LionRiddims]','dgUD9J6MxE0',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','akuma'],NULL,NULL,NULL,true),
('lucas-a-r-t-pedro-alvez-e','ARLEQUINA - Lucas A.R.T., Pedro Alvez e Gabriel Rodrigues [Prod. stardustszn]','drQ3BHjofpw',0,'7MZ RECORDS','7MZ',NULL,ARRAY['arlequina','lucas','a-r-t','pedro','alvez','gabriel','rodrigues'],NULL,NULL,NULL,true),
('dr-manhattan','Gabriel Rodrigues - DR. MANHATTAN [Prod. YUNG VENXM]','AYh_XAXGIMA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','dr','manhattan'],NULL,NULL,NULL,true),
('kratos-2','Gabriel Rodrigues - KRATOS [Prod. Soulker]','Xj3HOWKi5cw',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','kratos'],NULL,NULL,NULL,true),
('nemesis','Gabriel Rodrigues - NEMESIS [Prod. Instinct]','qfXFABdBeWo',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','nemesis'],NULL,NULL,NULL,true),
('bane','Gabriel Rodrigues - BANE [Prod. Karim Saidi]','rKqQN6IP7yA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','bane'],NULL,NULL,NULL,true),
('rei-do-crime-part-pablo-m','Gabriel Rodrigues - REI DO CRIME part. Pablo Matheuz e Pedro Alvez [Prod. YUNG VENXM]','mLhnw79l4RY',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','rei','crime','part','pablo','matheuz','pedro','alvez'],NULL,NULL,NULL,true),
('meu-malvado-favorito','Gabriel Rodrigues - MEU MALVADO FAVORITO [Prod. COBRA]','2iM7L2B0WCI',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','meu','malvado','favorito'],NULL,NULL,NULL,true),
('heisenberg','Gabriel Rodrigues - HEISENBERG [Prod. 808 Ander]','jDNRMo9mAKQ',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','heisenberg'],NULL,NULL,NULL,true),
('deadpool-2','Gabriel Rodrigues - DEADPOOL [Prod. Premise]','VzRaARM-xFE',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','deadpool'],NULL,NULL,NULL,true),
('toretto-part-lucas-a-r-t-','Gabriel Rodrigues - TORETTO part. Lucas A.R.T. [Prod. TheSkyBeats x 7ink]','i5XOmtHTqVM',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','toretto','part','lucas','a-r-t'],NULL,NULL,NULL,true),
('uchiha','Lucas A.R.T. - UCHIHA [Prod. Jurrivh]','2DwxW5jfXPA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','uchiha'],NULL,NULL,NULL,true),
('lucas-a-r-t-mhrap-gabriel','OUTRO PLANETA - Lucas A.R.T., MHRap, Gabriel Rodrigues e Pedro Qualy [Prod. Wall Hein]','WRSxo9cSdFc',0,'7MZ RECORDS','7MZ',NULL,ARRAY['outro','planeta','lucas','a-r-t','mhrap','gabriel','rodrigues','pedro','qualy'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-3','O MUNDO VAI SABER MEU NOME - Lucas A.R.T. e Gabriel Rodrigues (Game Over Squad Soundtrack)','Q8uE9i0aIQU',0,'7MZ RECORDS','7MZ',NULL,ARRAY['mundo','vai','saber','meu','nome','lucas','a-r-t','gabriel','rodrigues','game','over','squad','soundtrack'],NULL,NULL,NULL,true),
('lucas-a-r-t-mc-sid-rod-30','JOGADOR NÚMERO 1 - Lucas A.R.T., Mc Sid, Rod 3030 e Gabriel Rodrigues [Prod. 808 Ander]','6nSIp_aGHQ0',0,'7MZ RECORDS','7MZ',NULL,ARRAY['jogador','numero','lucas','a-r-t','sid','rod','3030','gabriel','rodrigues'],NULL,NULL,NULL,true),
('dama','GENKI-DAMA - Lucas A.R.T., Gabriel Rodrigues e DK47 [Prod. Gustavs Strazdins]','c78KGXFw1bQ',0,'7MZ RECORDS','7MZ',NULL,ARRAY['genki','dama','lucas','a-r-t','gabriel','rodrigues','dk47'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-4','ESCANOR - Lucas A.R.T. e Gabriel Rodrigues [Prod. Instinct]','iciIG5tw-hk',0,'7MZ RECORDS','7MZ',NULL,ARRAY['escanor','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('pablo-matheuz-pedro-alvez','MULTIVERSO - Pablo Matheuz, Pedro Alvez, Lucas A.R.T. e Gabriel Rodrigues [Prod. F8 Entertainment]','qZjpyc4upTE',0,'7MZ RECORDS','7MZ',NULL,ARRAY['multiverso','pablo','matheuz','pedro','alvez','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-pablo-matheuz','TRIBUTO AOS CLÁSSICOS - Lucas A.R.T., Pablo Matheuz e Gabriel Rodrigues [Prod. JpBeatz]','Gyroith0-Rc',0,'7MZ RECORDS','7MZ',NULL,ARRAY['tributo','aos','classicos','lucas','a-r-t','pablo','matheuz','gabriel','rodrigues'],NULL,NULL,NULL,true),
('herois','SUPER-HERÓIS - Lucas A.R.T. e Pedro Alvez [Prod. Tundra Beats]','JL5OwnRAieA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['super','herois','lucas','a-r-t','pedro','alvez'],NULL,NULL,NULL,true),
('pedro-alvez-lucas-a-r-t-e','ESFERAS DO DRAGÃO - Pedro Alvez, Lucas A.R.T. e Pablo Matheuz [Prod. Mantra & Zero Beatz]','a9-NSLcv69Y',0,'7MZ RECORDS','7MZ',NULL,ARRAY['esferas','dragao','pedro','alvez','lucas','a-r-t','pablo','matheuz'],NULL,NULL,NULL,true),
('lucas-a-r-t-pablo-matheuz-2','REI DOS PIRATAS - Lucas A.R.T., Pablo Matheuz, Pedro Alvez e Gabriel Rodrigues [Prod. KhronosBeats]','igiYhdq5zA8',0,'7MZ RECORDS','7MZ',NULL,ARRAY['rei','dos','piratas','lucas','a-r-t','pablo','matheuz','pedro','alvez','gabriel','rodrigues'],NULL,NULL,NULL,true),
('pablo-matheuz-lucas-a-r-t','SUITON - Pablo Matheuz, Lucas A.R.T. e Gabriel Rodrigues [Prod. Ihaksi]','LeOsJ4sIkUs',0,'7MZ RECORDS','7MZ',NULL,ARRAY['suiton','pablo','matheuz','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-5','HASHIRAMA - Lucas A.R.T. e Gabriel Rodrigues [Prod. Vamz Beatz]','3YNzEQnHGLA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['hashirama','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-6','TEMARI - Lucas A.R.T. e Gabriel Rodrigues [Prod. 808 Ander]','DRp6Q-cAQek',0,'7MZ RECORDS','7MZ',NULL,ARRAY['temari','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('katon','Lucas A.R.T. - KATON [Prod. 808 Ander]','FTrqVV7xOPo',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','katon'],NULL,NULL,NULL,true),
('vale-do-fim','Lucas A.R.T. - VALE DO FIM [Prod. 808 Ander]','v7lgtAaJsFg',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','vale','fim'],NULL,NULL,NULL,true),
('jinchuuriki','Lucas A.R.T. - JINCHUURIKI [Prod. 808 Ander]','XezKJpNL4Ac',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','jinchuuriki'],NULL,NULL,NULL,true),
('tsukuyomi-infinito','Lucas A.R.T. - TSUKUYOMI INFINITO [Prod. 808 Ander]','GzEy9Yt8iaw',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','tsukuyomi','infinito'],NULL,NULL,NULL,true),
('shippuden','Lucas A.R.T. - SHIPPUDEN [Prod. 808 Ander]','eiANVt-Kr_s',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','shippuden'],NULL,NULL,NULL,true),
('rinnegan','Lucas A.R.T. - RINNEGAN [Prod. Bonk Beatz]','8LLNdqZmRho',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','rinnegan'],NULL,NULL,NULL,true),
('kaguya','Lucas A.R.T. - KAGUYA [Prod. 808 Ander]','4HWYfd58f1o',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','kaguya'],NULL,NULL,NULL,true),
('lacos','Lucas A.R.T. - LAÇOS [Prod. 808 Ander]','MgTEJhd-CVY',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','lacos'],NULL,NULL,NULL,true),
('mangekyo-sharingan','Lucas A.R.T. - MANGEKYO SHARINGAN [Prod. 808 Ander]','C60uRO6ZfS8',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','mangekyo','sharingan'],NULL,NULL,NULL,true),
('pablo-matheuz-gabriel-rod','ALQUIMISTA - Pablo Matheuz, Gabriel Rodrigues, Lucas A.R.T. e Pedro Alvez [Prod. TheSkyBeats]','NNzgK7PT3fo',0,'7MZ RECORDS','7MZ',NULL,ARRAY['alquimista','pablo','matheuz','gabriel','rodrigues','lucas','a-r-t','pedro','alvez'],NULL,NULL,NULL,true),
('marca-da-maldicao','Gabriel Rodrigues - MARCA DA MALDIÇÃO [Prod. denz]','d_KbV_db5HA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['gabriel','rodrigues','marca','maldicao'],NULL,NULL,NULL,true),
('gabriel-rodrigues-pablo-m','DEATH NOTE - Gabriel Rodrigues, Pablo Matheuz e Lucas A.R.T. [Prod. 808 Ander]','IT0ksc-jJCc',0,'7MZ RECORDS','7MZ',NULL,ARRAY['death','note','gabriel','rodrigues','pablo','matheuz','lucas','a-r-t'],NULL,NULL,NULL,true),
('pedro-alvez-e-pablo-mathe','RICK & MORTY - Pedro Alvez e Pablo Matheuz [Prod. 808 Ander]','OJ4VSblsrnY',0,'7MZ RECORDS','7MZ',NULL,ARRAY['rick','morty','pedro','alvez','pablo','matheuz'],NULL,NULL,NULL,true),
('peu028-lucas-a-r-t-e-gabr','LOL - Peu028, Lucas A.R.T. e Gabriel Rodrigues [Prod. 808 Ander]','UgjpC7h1TCg',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lol','peu028','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('gabriel-rodrigues-e-lucas-2','SUSANOO - Gabriel Rodrigues e Lucas A.R.T. [Prod. 808 Ander]','oW4JCbcZ53M',0,'7MZ RECORDS','7MZ',NULL,ARRAY['susanoo','gabriel','rodrigues','lucas','a-r-t'],NULL,NULL,NULL,true),
('gabriel-rodrigues-e-lucas-3','SAMEHADA - Gabriel Rodrigues e Lucas A.R.T. [Prod. tunnA Beatz]','h4-HWKjEtGE',0,'7MZ RECORDS','7MZ',NULL,ARRAY['samehada','gabriel','rodrigues','lucas','a-r-t'],NULL,NULL,NULL,true),
('gabriel-rodrigues-lucas-a','BATMAN - Gabriel Rodrigues, Lucas A.R.T. e Rodrigo Zin [Prod. Dannyebtracks]','vqhtB7_JBfM',0,'7MZ RECORDS','7MZ',NULL,ARRAY['batman','gabriel','rodrigues','lucas','a-r-t','rodrigo','zin'],NULL,NULL,NULL,true),
('gabriel-rodrigues-e-lucas-4','TE FALTA ÓDIO - Gabriel Rodrigues e Lucas A.R.T. [Prod. bezimenimusic]','dNCO-UgMu6A',0,'7MZ RECORDS','7MZ',NULL,ARRAY['falta','odio','gabriel','rodrigues','lucas','a-r-t'],NULL,NULL,NULL,true),
('iron-man-2','Lucas A.R.T. - IRON MAN [Prod. 808 Ander]','kFLyzob42uU',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','iron','man'],NULL,NULL,NULL,true),
('lucas-a-r-t-pedro-alvez-g','AKATSUKI - Lucas A.R.T., Pedro Alvez, Gabriel Rodrigues e Pablo Matheuz [Prod. Tundra Beats]','o7tRFYZdndw',0,'7MZ RECORDS','7MZ',NULL,ARRAY['akatsuki','lucas','a-r-t','pedro','alvez','gabriel','rodrigues','pablo','matheuz'],NULL,NULL,NULL,true),
('cola','COCA-COLA - Lucas A.R.T., Gabriel Rodrigues e Pedro Alvez [Prod. Zero]','eATIQbRYvqs',0,'7MZ RECORDS','7MZ',NULL,ARRAY['coca','cola','lucas','a-r-t','gabriel','rodrigues','pedro','alvez'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-7','ANNABELLE - Lucas A.R.T. e Gabriel Rodrigues [Prod. Aksil]','U7N6BzN-oqI',0,'7MZ RECORDS','7MZ',NULL,ARRAY['annabelle','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-pablo-mathe','YONDAIME - Lucas A.R.T. e Pablo Matheuz [Prod. Bonk Beatz]','4koMm_F13AA',0,'7MZ RECORDS','7MZ',NULL,ARRAY['yondaime','lucas','a-r-t','pablo','matheuz'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-8','OTAKU - Lucas A.R.T. e Gabriel Rodrigues [Prod. 808 Ander]','xZuoYZBZljI',0,'7MZ RECORDS','7MZ',NULL,ARRAY['otaku','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-pablo-matheuz-3','FÊNIX - Lucas A.R.T., Pablo Matheuz, Pedro Alvez e Gabriel Rodrigues [Prod. John Savage]','fYEhUsRZXhE',0,'7MZ RECORDS','7MZ',NULL,ARRAY['fenix','lucas','a-r-t','pablo','matheuz','pedro','alvez','gabriel','rodrigues'],NULL,NULL,NULL,true),
('gabriel-rodrigues-e-lucas-5','MANGÁ - Gabriel Rodrigues e Lucas A.R.T. [Prod. hlbak]','i5hc-o0GYTM',0,'7MZ RECORDS','7MZ',NULL,ARRAY['manga','gabriel','rodrigues','lucas','a-r-t'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-9','CORINGA - Lucas A.R.T. e Gabriel Rodrigues [Prod. Bonk Beatz]','5QgUdsZvsSk',0,'7MZ RECORDS','7MZ',NULL,ARRAY['coringa','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-10','ALADDIN - Lucas A.R.T. e Gabriel Rodrigues [Prod. MaaBeatz]','U_OHtl-DESg',0,'7MZ RECORDS','7MZ',NULL,ARRAY['aladdin','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-pablo-matheuz-4','THANOS - Lucas A.R.T., Pablo Matheuz e Gabriel Rodrigues [Prod. Bonk Beatz]','cJp5y4uHbo8',0,'7MZ RECORDS','7MZ',NULL,ARRAY['thanos','lucas','a-r-t','pablo','matheuz','gabriel','rodrigues'],NULL,NULL,NULL,true),
('gabriel-rodrigues-e-lucas-6','RAP DE CRIANÇA - Gabriel Rodrigues e Lucas A.R.T. [Prod. play dead]','3Ramk0zuObU',0,'7MZ RECORDS','7MZ',NULL,ARRAY['rap','crianca','gabriel','rodrigues','lucas','a-r-t'],NULL,NULL,NULL,true),
('baby-eu-nao-te-amo-mais-p','Lucas A.R.T. - BABY, EU NÃO TE AMO MAIS [Prod. Gold','nWKQkY00DjI',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','baby','nao','amo','mais'],NULL,NULL,NULL,true),
('7-minutoz-player-tauz-vmz','NERDSTAR - 7 Minutoz, Player Tauz, VMZ e Felícia Rock','LAWpTN2Z03o',0,'7MZ RECORDS','7MZ',NULL,ARRAY['nerdstar','minutoz','player','tauz','vmz','felicia','rock'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-11','INSTINTO SUPERIOR - Lucas A.R.T. e Gabriel Rodrigues [Prod. John Savage]','a8No3V_oKig',0,'7MZ RECORDS','7MZ',NULL,ARRAY['instinto','superior','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;