INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('m4rkim-NbdypbbksAg','Satoru Gojo (Jujutsu Kaisen) - INFINITØ | M4rkim','NbdypbbksAg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-YYOzEPf8AAM','Katakuri (One Piece) - Doce Visão Do Futuro | M4rkim','YYOzEPf8AAM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-yFpNY-2lpRQ','Chihiro Rokuhira (Kagurabachi) - Espadas, Magias & Vingança | M4rkim','yFpNY-2lpRQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-UDgM5NORRdk','Apolo (Shuumatsu no Valkyrie) - Sol | M4rkim','UDgM5NORRdk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim--ekmqjB4QvM','Comandantes (One Piece) - Braço Direito | M4rkim','-ekmqjB4QvM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-o0tCHzlLkwo','Gohan (Dragon Ball Z) - Saiyajin 2 | M4rkim','o0tCHzlLkwo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-z4pYbkdZAys','Tomie (Junji Ito) - Desejos Insanos | M4rkim & Anny','z4pYbkdZAys',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-DDv-6A-2iiQ','Kenjaku (Jujutsu Kaisen) - Corpo Morto | M4rkim','DDv-6A-2iiQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-97XD1MnFA40','Tanjiro, Zenitsu e Inosuke (Kimetsu no Yaiba) - Caçadores De Oni | M4rkim feat. Basara & Daarui','97XD1MnFA40',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-iuj9Diz4MN8','Crocodile (One Piece) - Rei Do Deserto | M4rkim','iuj9Diz4MN8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-JIvN9_imjjg','Musashi Miyamoto (Vagabond) - Caminho Da Morte | M4rkim','JIvN9_imjjg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-s_JayV32_-A','Guts (Berserk) - Perdi Tudo | M4rkim','s_JayV32_-A',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-HOJdqxbXoso','Gilgamesh (Fate) - Portões Da Babilônia | M4rkim','HOJdqxbXoso',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-aRQkCVYg7VI','Sukuna (Jujutsu Kaisen) - Rei Das Maldições | M4rkim','aRQkCVYg7VI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-5NLDYn1aAhY','Luffy (One Piece) - Quinta Marcha | M4rkim','5NLDYn1aAhY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-mjqSF0Bt1iU','Lord Drakkon (Power Rangers) - Deus | M4rkim','mjqSF0Bt1iU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-9YqmS50lFJ0','Ben 10 (Ben 10) - Omnitrix | M4rkim','9YqmS50lFJ0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim--Xm7rmVK9v4','Suguru Geto (Jujutsu Kaisen) - Espiral | M4rkim','_Xm7rmVK9v4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-y5Vm3J37C6c','Asta (Black Clover) - 5 Folhas | M4rkim','y5Vm3J37C6c',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ziMWNe52DCk','Homem-Aranha 2099 (Homem-Aranha: Através do Aranhaverso) - Futuro | M4rkim','ziMWNe52DCk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-68aNlmWi828','Genya Shinazugawa (Kimetsu no Yaiba) - Mira Do Caçador | M4rkim','68aNlmWi828',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-LmitbkoThQ0','Barba Negra (One Piece) - Sonhos & Escuridão | M4rkim','LmitbkoThQ0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Q65HIpA6eNc','Johnny Joestar (Jojo','Q65HIpA6eNc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-G54DZL2XpbQ','Vilões (One Piece) - Ambição | M4rkim','G54DZL2XpbQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Qs5xNmzXKfE','Hantengu (Kimetsu no Yaiba) - Lua Superior Quatro | M4rkim','Qs5xNmzXKfE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-U8i2_6gG110','Gon x Neferpitou (Hunter X Hunter) - Homem Gentil | M4rkim feat. Mistery','U8i2_6gG110',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-A3R_vc7ndo0','Vegetto (Dragon Ball Z) - Saiyajins | M4rkim feat. Basara','A3R_vc7ndo0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-PXuFihe21tc','Ekko (League of Legends) - Tempo | M4rkim','PXuFihe21tc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-XeI7bJwtntY','Kawaki Uzumaki (Boruto) - Karma | M4rkim','XeI7bJwtntY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-pbPqe6doxhk','Itadori & Todo (Jujutsu Kaisen) - My Brother | M4rkim feat. Kaito​','pbPqe6doxhk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-RMXZiiTHdn8','Law (One Piece) - Cirurgião Da Morte | M4rkim','RMXZiiTHdn8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-wvg0M57cakc','Lampião (Lampião) - Rei Do Cangaço | M4rkim','wvg0M57cakc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-t0EnKI4KK5w','Nikola Tesla (Shuumatsu no Valkyrie) - Luz Da Esperança | M4rkim','t0EnKI4KK5w',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-3kB3z8RLt_M','Kaneki (Tokyo Ghoul) - Faminto | M4rkim','3kB3z8RLt_M',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-FIufxjfejfo','Yoriichi (Kimetsu no Yaiba) - Sol Da Noite | M4rkim','FIufxjfejfo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-8Qh2wGrmDWA','Barou (Blue Lock) - Rei Egoísta | M4rkim','8Qh2wGrmDWA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZlBpQldO9i0','Beelzebub (Shuumatsu no Valkyrie) - Moscas | M4rkim','ZlBpQldO9i0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ToejjD4UAjI','Denji (Chainsaw Man) - Demônio Motosserra | M4rkim','ToejjD4UAjI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-fPuDTdQZzKk','Doflamingo (One Piece) - Por Um Fio | M4rkim','fPuDTdQZzKk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-SRgEcwurZGQ','Goku (Dragon Ball GT) - Saiyajin 4 | M4rkim','SRgEcwurZGQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-d075cooe68s','Darth Vader (Star Wars) - Lado Negro | M4rkim','d075cooe68s',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-VgUDOJ_9wmM','Seto Kaiba (Yu-Gi-Oh!) - Olhos Azuis | M4rkim','VgUDOJ_9wmM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-pXiJhadVshs','Aizen (Bleach) - Ilusão | M4rkim','pXiJhadVshs',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Adf7Do4Uj04','Arthur Cervero (Ordem Paranormal) - Abutre | M4rkim','Adf7Do4Uj04',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-dnl7R90M-Kg','Vilões (Dragon Ball Z) - Poder | M4rkim','dnl7R90M-Kg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-w0u134iUhY4','Musashi Miyamoto (Vagabond) - Caminho Da Espada | M4rkim','w0u134iUhY4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-JQZ7oGVFPQY','Satoru Gojo (Jujutsu Kaisen) - Infinito | M4rkim','JQZ7oGVFPQY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-hFU9Tu6Y0Pg','Enel (One Piece) - Energia | M4rkim','hFU9Tu6Y0Pg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-j_Ur5TRxDdM','Hashirama (Naruto) - Konoha | M4rkim','j_Ur5TRxDdM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZNpTHk7zfzE','Yuta Okkotsu (Jujutsu Kaisen) - Rainha Das Maldições | M4rkim feat. Anny','ZNpTHk7zfzE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-lUnrcrpSEhc','Goku (Dragon Ball Z) - Saiyajin | M4rkim','lUnrcrpSEhc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-kQtKTZn9tI0','Hashiras x Kokushibou (Kimetsu no Yaiba) - Castelo Infinito | M4rkim','kQtKTZn9tI0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-iLFdTal1Wfo','Orochimaru (Naruto) - Serpente | M4rkim','iLFdTal1Wfo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-tyVvUFcUtrw','Máskara (The Mask) - Máscara | M4rkim','tyVvUFcUtrw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-SPi9XmAjKo0','Muzan (Kimetsu no Yaiba) - Impronunciável | M4rkim','SPi9XmAjKo0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-3M0qJYY_Vu4','Buda (Shuumatsu no Valkyrie) - Iluminação | M4rkim','3M0qJYY_Vu4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-G4UAfQcm94o','Garou Cósmico (One Punch Man) - Cosmic | M4rkim','G4UAfQcm94o',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim--IDzs6GncUk','Kaidou (One Piece) - 100 Feras | M4rkim','-IDzs6GncUk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-kGqaOHmlG98_2','Vecna (Stranger Things) - 001 | M4rkim','kGqaOHmlG98',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZmXc_751pCA_2','Billy Bruto (The Boys) - Brutalmente | M4rkim','ZmXc_751pCA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-e6JIPQOrwiM','Kang O Conquistador (Marvel Comics) - Linha Do Tempo | M4rkim','e6JIPQOrwiM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-BqtnwQHCKiU','Akashi (Kuroko no Basket) - Zu Ga Takai Zo | M4rkim','BqtnwQHCKiU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-QCu5OD8n8c4','Hades (Shuumatsu no Valkyrie) - Submundo | M4rkim','QCu5OD8n8c4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-EQNPS4TtTzA','Qin Shi Huang (Shuumatsu no Valkyrie) - China | M4rkim','EQNPS4TtTzA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-iG_Yt6CJpXQ','Blade (Marvel Comics) - Óculos No Show | M4rkim','iG_Yt6CJpXQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-6rbGhsfpVgA','Anti-Heróis (Marvel Comics) - Do Meu Jeito | URT','6rbGhsfpVgA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ysFNnNGdiwA','Majin Boo (Dragon Ball Z) - Vou Te Comer | M4rkim','ysFNnNGdiwA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-3rxEC_TOfj8','Fushiguro Toji (Jujutsu Kaisen) - Só Basta Pagar | M4rkim','3rxEC_TOfj8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-T5w4dv_ag0s','Naofumi (Tate No Yuusha) - Herói Do Escudo | M4rkim','T5w4dv_ag0s',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-b6EcLIT-KU0','Injustice (DC Comics) - Deuses Entre Nós | M4rkim ft. @BasaraMusic & @AniRap','b6EcLIT-KU0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-VMBah8W3YSM','Barba Branca (One Piece) - Irá Tremer | M4rkim','VMBah8W3YSM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-NuS8uHuHUhI','Motoqueiro Fantasma (Marvel Comics) - Motor | M4rkim','NuS8uHuHUhI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-w1_erhAgduA','Madara (Naruto) - Tsukuyomi | M4rkim','w1_erhAgduA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZIWddvYRoho','Vegeta (Dragon Ball Z) - Pura Maldade | M4rkim','ZIWddvYRoho',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-RcSpDpM7uLQ','Venom (Marvel Comics) - Simbiose | M4rkim ft. @Enygma_Music','RcSpDpM7uLQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Mb7IN5f7zw8','Levi (Shingeki no Kyojin) - Capitão | M4rkim','Mb7IN5f7zw8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-zybkqL0rH9I','Tengen Uzui (Kimetsu no Yaiba) - Deus Da Extravagância | M4rkim','zybkqL0rH9I',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ixBtmmuL-88','Griffith (Berserk) - Falcão Branco | M4rkim (@HunterMsc)','ixBtmmuL-88',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-jt_P3HFVTaw','Erwin Smith (Shingeki no Kyojin) - Sasageyo | M4rkim','jt_P3HFVTaw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ouuaEALaaGg','Batman Que Ri (DC Comics) - Piada Mortal | M4rkim','ouuaEALaaGg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-M2gPfhthsHw','Sung Jin Woo (Solo Leveling) - O Monarca Das Sombras | Parte Final | M4rkim (@HunterMsc)','M2gPfhthsHw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZSE0szAYEbo','Shiva (Shuumatsu no Valkyrie) - Deus Da Destruição | M4rkim','ZSE0szAYEbo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-K0OtoZ6RfWU','Garou (One Punch Man) - Monstro Humano | M4rkim','K0OtoZ6RfWU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-xZPoJKVmU3s','Douma (Kimetsu no Yaiba) - Lua Superior Dois | M4rkim','xZPoJKVmU3s',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-SKZAbx9YIOo','Tooru (Jojo','SKZAbx9YIOo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim--tSimR7EZRY','Yujiro (Baki The Grappler) - O Melhor | M4rkim','-tSimR7EZRY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-XD4nDM2h65U','Power (Chainsaw Man) - A Possessa Do Sangue | M4rkim','XD4nDM2h65U',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-v9BY-9v9S5w','Jinx (Arcane) - Meu Inimigo | M4rkim','v9BY-9v9S5w',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-0nKd_VhfhWY','Baki (Baki The Grappler) - O Campeão | M4rkim','0nKd_VhfhWY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-9ajjmBPez3U','Yonkou (One Piece) - Imperador Do Mar | URT','9ajjmBPez3U',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-7KyRAKAPEtg','Gon (Hunter x Hunter) - Caçador | M4rkim','7KyRAKAPEtg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-TvpDw-frmVk','Funny Valentine (Jojo','TvpDw-frmVk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-tDAtH3Mh5n4','Keisuke Baji (Tokyo Revengers) - Minha Gangue | M4rkim','tDAtH3Mh5n4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-pHur8zW1VVA','Corazon (One Piece) - Sua Cura | M4rkim','pHur8zW1VVA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Gpy8i0lx4U4','Saber (Fate) - Excalibur | M4rkim','Gpy8i0lx4U4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim--v-ZrAQARD4','Jack O Estripador (Shuumatsu no Valkyrie) - Londres | M4rkim','-v-ZrAQARD4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-k07X7elFBRI','Meruem (Hunter x Hunter) - Um Rei | M4rkim','k07X7elFBRI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-9nhM78-LyV8','Sanji (One Piece) - All Blue | M4rkim','9nhM78-LyV8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-njZl3Yrhxsg','Hitsugaya (Bleach) - Asas De Gelo | M4rkim','njZl3Yrhxsg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-vBEMl1DUOLY','Diavolo (Jojo','vBEMl1DUOLY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;