INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('pedro-alvez-lucas-a-r-t-e-2','KAKASHI - Pedro Alvez, Lucas A.R.T. e Gabriel Rodrigues [Prod. Zero]','XkTmwNsNdao',0,'7MZ RECORDS','7MZ',NULL,ARRAY['kakashi','pedro','alvez','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('friendzone','Lucas A.R.T. - FRIENDZONE [Prod. Ecologyk]','QTIg3Cevt40',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','a-r-t','friendzone'],NULL,NULL,NULL,true),
('lagrimas-serao-sorrisos','Lucas ART - Lágrimas Serão Sorrisos','eAD7MKhpLjY',0,'7MZ RECORDS','7MZ',NULL,ARRAY['lucas','art','lagrimas','serao','sorrisos'],NULL,NULL,NULL,true),
('lucas-a-r-t-pablo-matheuz-5','FLASH - Lucas A.R.T., Pablo Matheuz, Pedro Alvez e Gabriel Rodrigues [Prod. Rizzi & Drama 808]','wzYwzwSlk_c',0,'7MZ RECORDS','7MZ',NULL,ARRAY['flash','lucas','a-r-t','pablo','matheuz','pedro','alvez','gabriel','rodrigues'],NULL,NULL,NULL,true),
('lucas-a-r-t-e-gabriel-rod-12','AMATERASU - Lucas A.R.T. e Gabriel Rodrigues [Prod. Paradox]','BsWcLYc-Vk4',0,'7MZ RECORDS','7MZ',NULL,ARRAY['amaterasu','lucas','a-r-t','gabriel','rodrigues'],NULL,NULL,NULL,true),
('m4rkim-nrVsbd310QA','M4rkim - ADRENALINA (Kaleb)','nrVsbd310QA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-nsIFsLjVBR4','M4rkim - EXPANSÃO DE DOMÍNIO (Dabura Karaba)','nsIFsLjVBR4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZX4cMht0aow','M4rkim - SANGUE HANMA (Baki)','ZX4cMht0aow',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-nHmgNWfx7Vw','M4rkim - UBERS (Blue Lock)','nHmgNWfx7Vw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-FTCgrnqp96E','M4rkim - DAVY D. JONES (Rocks D. Xebec)','FTCgrnqp96E',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-nwTm5r24DUg','M4rkim - Paris X Gen (Blue Lock)','nwTm5r24DUg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-f0hV0mBsD2Q','M4rkim - Terpsichora (Neferpitou)','f0hV0mBsD2Q',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-3tK_QrhXdUQ','M4rkim - Capítulo 01 (Fortnite)','3tK_QrhXdUQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ExsBA7-vYfU','M4rkim - Los Lobos (Coyote Starrk)','ExsBA7-vYfU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-H1qb-OB7-z0','M4rkim - Os Cinco Mais Fortes (Baki the Grappler)','H1qb-OB7-z0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-qJP2Ogf-tNQ','M4rkim - Minecraft (Steve)','qJP2Ogf-tNQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Y-c6a7U7gxw','M4rkim - Bastard München (Blue Lock)','Y-c6a7U7gxw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-yCjjtrMKpR8','M4rkim - METAVISÃO (Isagi Yoichi)','yCjjtrMKpR8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-F1Iuri-d1kU','M4rkim - Psychic (Silver o Ouriço)','F1Iuri-d1kU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ntkwhrhXlXE','M4rkim - Ragnarok (Kratos)','ntkwhrhXlXE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-bSYmlG5jGn8','M4rkim - Vilão Do Cenário (Barou Shoei)','bSYmlG5jGn8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-5QormbKxYiI','M4rkim - Marineford (One Piece)','5QormbKxYiI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-B7U_SSuqP-c','M4rkim - Minha Máskara! (Jujutsu Lock)','B7U_SSuqP-c',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-GnWKK50nHQg','M4rkim - Lua Superior Três (Akaza)','GnWKK50nHQg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-dk-iWDRGYmE','M4rkim - Castelo Infinito 2 (Akaza x Tanjiro e Tomioka)','dk-iWDRGYmE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-rCuG3Lj7inA','M4rkim - Bully (Jimmy Hopkins)','rCuG3Lj7inA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-obq4zIb2cN0','M4rkim - Ømnitrix','obq4zIb2ZER0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-nq_BNXlBjVQ','M4rkim - Criador (Arceus)','nq_BNXlBjVQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-JGmO8o04QS4','M4rkim - Mentiroso (Loki)','JGmO8o04QS4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-zcfH57lz_u8','M4rkim - Morte Branca (Simo Häyhä)','zcfH57lz_u8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-4bf0GW5KQnE','M4rkim - Impecável (Itoshi Sae)','4bf0GW5KQnE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-2nmMhskfP7g','M4rkim - Incrível (Itoshi Rin)','2nmMhskfP7g',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-u6T33wvvj0Y','M4rkim - Paradisíaco (Rudo Surebrec)','u6T33wvvj0Y',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-f-9G5vtlG5U','M4rkim - Mutile, Pantera! (Grimmjow)','f-9G5vtlG5U',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Ms3V_bL6erw','M4rkim - Trio Da Criação (Pokémon)','Ms3V_bL6erw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ypsUvsnIvg4','M4rkim - Batalhas Épicas (Álbum Completo)','ypsUvsnIvg4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim--3QiuFYBe4Q','Rá (Shuumatsu no Valkyrie - Gods','-3QiuFYBe4Q',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-NGK7aWLTUIA','João (Tales of Destruction) - Maria | M4rkim','NGK7aWLTUIA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-5ylXqAQ7pWM','Cú Chulainn x Rá (Shuumatsu no Valkyrie - Gods','5ylXqAQ7pWM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-fFNv_GlIMtE','Chris Prince (Blue Lock) - Corpo Perfeito | M4rkim','fFNv_GlIMtE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-pYlQ4Jarzcc','Pinóquio (Tales of Destruction) - Mentiras | M4rkim','pYlQ4Jarzcc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-xEPhklFUQE8','Ben 10 (Ben 10: Omniverse) - Omnitrix','xEPhklFUQE8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-OjfZ7adQBPY','Cell (Dragon Ball Z) - D.N.A | M4rkim','OjfZ7adQBPY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-H3JoRuT5ruA','Sung Jin Woo (Solo Leveling) - Monarca Das Sombras | M4rkim','H3JoRuT5ruA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-88FtdnupGBI','Vegeta (Dragon Ball Super) - Ultra Ego | M4rkim','88FtdnupGBI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-4nN-hnsieGQ','Ranger Da Morte (Power Rangers) - Deus Da Morte | M4rkim','4nN-hnsieGQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-OAaJcgty4Is','Urahara (Bleach) - Benihime | M4rkim','OAaJcgty4Is',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-TbDKtVeUmV4','Dante (Devil May Cry) - Jackpot! | M4rkim','TbDKtVeUmV4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-nHPhRyjBwaE','Yuta Okkotsu (Jujutsu Kaisen) - Puro Amor Infinito | M4rkim','nHPhRyjBwaE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-w6IsMawxLoQ','Roronoa Zoro (One Piece) - 3 Sonhos, 3 Espadas | M4rkim','w6IsMawxLoQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-tD7BSSTIR1M','Sanji (One Piece) - All Blue | M4rkim','tD7BSSTIR1M',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-7z3rjVFULpI','Mugiwaras (One Piece) - Chapéu De Palha | M4rkim','7z3rjVFULpI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-oFnkPuOZ98M','Shadow (Sonic) - Caos | M4rkim','oFnkPuOZ98M',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-MfRyetHMvtg','Feiticeiros (Jujutsu Kaisen) - Amaldiçoados | M4rkim','MfRyetHMvtg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-sdUNCOMoVoE','Kratos (God of War) - Ruína Dos Deuses | M4rkim','sdUNCOMoVoE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-I21a2cbzjGk','Isagi Yoichi (Blue Lock) - Egoísta | M4rkim','I21a2cbzjGk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Tk44NTYsrbw','Escanor (Nanatsu no Taizai) - Pecado Do Orgulho | M4rkim','Tk44NTYsrbw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-C5d3cuc5ZeQ','Susano','C5d3cuc5ZeQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-tiH-gzRCK10','Sonic.exe (Creepypasta) - SEGA 6.6.6 | M4rkim','tiH-gzRCK10',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-2lSgWitCCqo','Eustass Kid (One Piece) - Punk Gibson! | M4rkim','2lSgWitCCqo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-0C4438sQ904','Ben 10 (Ben 10: Supremacia Alienígena) - Super Omnitrix | M4rkim','0C4438sQ904',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-R35KGQT3fT8','Naruto x Pain (Naruto Shippuden) - Conto De Um Ninja Destemido | M4rkim feat. Okabe','R35KGQT3fT8',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-VN4zzCsR0JQ','Sukuna (Jujutsu Kaisen) - Santuário Malevolente | M4rkim','VN4zzCsR0JQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-pwImFrAx6n0','Itadori Yuji (Jujutsu Kaisen) - Santuário | M4rkim','pwImFrAx6n0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-M86lsT2XXlM','Higuruma (Jujutsu Kaisen) - Tribunal Das Almas | M4rkim','M86lsT2XXlM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ki8R9KM7OLg','Among Us (Among Us) - Impostor | M4rkim','ki8R9KM7OLg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-tbhsAiNwq0E','Vilões (Animes) - Coração Sujo | M4rkim','tbhsAiNwq0E',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-fzCLoPC3eHw','Adão (Shuumatsu no Valkyrie) - No.00000000001 | M4rkim','fzCLoPC3eHw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ePCK5q0lo1g','Ulquiorra (Bleach) - Murciélago | M4rkim','ePCK5q0lo1g',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-1KPEV2aObVQ','Xicrinho e Caneco (Cuphead) - Seus Dados | M4rkim & VMZ','1KPEV2aObVQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-E6Jlr3imEjU','Ace (One Piece) - Punhos De Fogo | M4rkim','E6Jlr3imEjU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-7OfUP4KeVRE','Broly (Dragon Ball Super) - Super Saiyajin Lendário | M4rkim','7OfUP4KeVRE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-78PUNClpM4E','Kafka Hibino (Kaiju No. 8) - Abalo Sísmico | M4rkim','78PUNClpM4E',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-bRCG76HANZc','Herobrine (Minecraft) - Sua Pele & Olhos Brancos | M4rkim','bRCG76HANZc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-TgqAoAUZWfA','Musashi Miyamoto (Vagabond) - Caminho Da Alma | M4rkim','TgqAoAUZWfA',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-YDd9IARCFdo','A-Kira (Death Note) - Ju$tiça | M4rkim','YDd9IARCFdo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-YpZHSv4PvD0','Arthur Morgan (Red Dead Redemption 2) - Morte e Redenção | M4rkim','YpZHSv4PvD0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Ne8_6LH9i0E','Dio Brando (JoJo','Ne8_6LH9i0E',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-Rrr5MTcMy_A','Eren (Shingeki no Kyojin) - Fim Da Humanidade | M4rkim | O Epílogo','Rrr5MTcMy_A',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-zpi1DYAq9RQ','Naruto (Naruto) - Sétimo Hokage | M4rkim','zpi1DYAq9RQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-1ECTTSYkFVw','Rob Lucci (One Piece) - Selvagem | M4rkim','1ECTTSYkFVw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-zzLrHzJrSi4','Kaneki (Tokyo Ghoul) - FAMINTØ | M4rkim','zzLrHzJrSi4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-KFttScr6en0','Michael, Franklin & Trevor (Grand Theft Auto) - 𝐕 | M4rkim feat. Henrique Mendonça e Daarui','KFttScr6en0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-uuGMX8EbmYE','Makima (Chainsaw Man) - Demônio Controle | M4rkim','uuGMX8EbmYE',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-X4IhAfcdIao','Luffy, Zoro, Sanji & Jinbe (One Piece) - Quarteto Monstro | M4rkim','X4IhAfcdIao',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-rcSWmexBgAI','Ezreal (League of Legends) - Real & Mágico | M4rkim','rcSWmexBgAI',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-48goYgqmeSU','Yhwach (Bleach) - 9.9.9 | M4rkim','48goYgqmeSU',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-WobsJtyKPIo','Hellboy (Hellboy) - Bom Samaritano | M4rkim','WobsJtyKPIo',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-CvlLKcY16qY','Finn (Hora de Aventura) - Mundo De Ooo | M4rkim','CvlLKcY16qY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-s3ujFKd8f28','Ichigo (Bleach) - Zangetsu | M4rkim','s3ujFKd8f28',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-0ihSPjRwbFQ','Ben 10 (Ben 10: Força Alienígena) - ØMNITRIX | M4rkim','0ihSPjRwbFQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-war37uaynus','Yuta Okkotsu (Jujutsu Kaisen) - Puro Amor | M4rkim','war37uaynus',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-ZKaC2-k1ves','Sasuke (Naruto) - Sharingan | M4rkim','ZKaC2-k1ves',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-6DctEuL2Pjc','Luffy (One Piece) - Rei Dos Piratas | M4rkim','6DctEuL2Pjc',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-sFOZI6aKspk','Humanos (Shuumatsu no Valkyrie) - Humanidade | M4rkim','sFOZI6aKspk',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-rPUJabfZfQg','Gasparzinho (Gasparzinho O Fantasminha Camarada) - Sem Camaradas | M4rkim','rPUJabfZfQg',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-lTrQrJYx6e4','Shaka de Virgem (Os Cavaleiros do Zodíaco) - Sentidos | M4rkim','lTrQrJYx6e4',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-vvhX-bfjFBM','CJ (Grand Theft Auto) - San Andreas | M4rkim','vvhX-bfjFBM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-npxABqbmfcY','Guts (Berserk) - Berserk | M4rkim','npxABqbmfcY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-_rPJK87ptio','Netero x Meruem (Hunter X Hunter) - Monstro Humano | M4rkim feat. Daarui','_rPJK87ptio',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;