INSERT INTO public.songs (id,title,youtube_id,duration,category,artist_id,anime,search_terms,intro_skip,outro_buffer,selos,active) VALUES
('m4rkim-SlGsXfoHWaY','Draken/Ken Ryuguki (Tokyo Revengers) - Um Dragão | M4rkim','SlGsXfoHWaY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-NBFIzaFfIR0','Yoshikage Kira (Jojo','NBFIzaFfIR0',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-8DM8e6SN5XY','Poseidon (Shuumatsu no Valkyrie) - O Comandante Do Mar | M4rkim','8DM8e6SN5XY',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-e3qXdLlkpdw','Rap do Satoru Gojo (Jujutsu Kaisen) - Roxo | Prod. theskybeats |','e3qXdLlkpdw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-oB6yqvfUu3U','Rap do Sung Jin Woo (Solo Leveling) - O Monarca Das Sombras | Prod. WB Beats |','oB6yqvfUu3U',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-JM2t0VWernw','Rap do Hyakkimaru (Dororo) - Chamas | Prod. COBRA |','JM2t0VWernw',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-kv3re9aI36I','Rap do Rock Lee (Naruto) - Trabalho Duro','kv3re9aI36I',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-1zwiLezHYtQ','Rap do Netero (Hunter x Hunter) - Gratidão | Prod. theskybeats |','1zwiLezHYtQ',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('m4rkim-G3GJCkoUpVM','Rap do Eren (Shingeki no Kyojin) - A Salvação da Humanidade | Prod. Artisans | O Prólogo','G3GJCkoUpVM',0,'M4RKIM','M4RKIM',NULL,NULL,NULL,NULL,NULL,true),
('anirap-aiwwH7cPkEw','♪ Desabafo: Majin Vegeta (DBZ) | Sacrifício | AniRap','aiwwH7cPkEw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-T4fU8HsyKBs','♪ Hakari Kinji (Jujutsu Kaisen) | O Dobro ou Nada | AniRap','T4fU8HsyKBs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-5d6B4A642RU','♪ Hugo (Blue Lock) | Engrenagem | AniRap','5d6B4A642RU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-tIN-pMvFPR4','♪ Buda e Wukong (Shuumatsu no Valkyrie) | Iluminação  | AniRap e @KaitoOFC','tIN-pMvFPR4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-zS8PVdBSdOA','♪ Itadori & Yuta (Jujutsu Kaisen) | Maldição Herdada | AniRap','zS8PVdBSdOA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ZoLarZ_8I1U','♪ Vigilante (Pacificador) | M4TEI FOI POUCO | AniRap','ZoLarZ_8I1U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-V2eC7LzhObc','♪ Izana Kurokawa (Tokyo Revengers) | Vazio | AniRap','V2eC7LzhObc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-YdJelGS9Yjw','♪ Mirai Trunks (Dragon Ball Z) | Última Luz do Futuro | AniRap','YdJelGS9Yjw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-IE8gUz1txIA','♪ Barou Shoei (Blue Lock) | Predador | AniRap','IE8gUz1txIA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ghwXav8-WRw','♪ Nova Ordem (Animes) | AniRap','ghwXav8-WRw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-6TjYpExBB2U','♪ Obito Uchiha (Naruto Shippuden) | Pesadelo | AniRap e @ishidaoficial','6TjYpExBB2U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-K9cbdSCi1NA','♪ Simo Häyhä (Shuumatsu no Valkyrie) | PAPOCO DE 40TÃO | AniRap','K9cbdSCi1NA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-4q-Nl7B98GY','♪ Legado (Rainbow Six) | AniRap e @Hawkyyy','4q-Nl7B98GY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-dHtzO4AmDQQ','♪ Akaza (Kimetsu no Yaiba) | Inquebrável | AniRap','dHtzO4AmDQQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-l0VAI6V0qec','♪ Charles e Shidou (Blue Lock) | Jogada Perversa | AniRap & Ark King','l0VAI6V0qec',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-EqHHUFpfpPM','♪ Fushiguro Toji (Jujutsu Kaisen) | FAZ O PIX | AniRap','EqHHUFpfpPM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-MAMLdoqmZKM','♪ LIGA NEO EGOISTA (Blue Lock) | COMPLETO | AniRap','MAMLdoqmZKM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-4y66cLYIeXg','♪ Bastard X PXG ( Blue Lock ) | Liga Neo Egoísta PT 4 | AniRap','4y66cLYIeXg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-IQr0b4E5s-U','♪ Saitama (One Punch Man) | Soco  Seriamente Sério  | AniRap','IQr0b4E5s-U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-uiDYHcJYT70','♪ Zenitsu (Demon Slayer) | Olhos Abertos | AniRap','uiDYHcJYT70',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-w6uvYEoC-LU','♪ Bastard X Ubers (Blue Lock) | Liga Neo Egoísta PT 3 | AniRap','w6uvYEoC-LU',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-wRHsFCERYZ8','♪ Kidpool (Finge que é Blue Lock) | Ado ado ado 2 | AniRap','wRHsFCERYZ8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-3z0_5vIQpnk','♪ Loki (Shuumatsu no Valkyrie) | Mentiras | AniRap FT. @nikmouu e @LHzZ','3z0_5vIQpnk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-rINBhARXFH8','♪ Bastard X Manshine City (Blue Lock) | Liga Neo Egoísta PT 2 | AniRap','rINBhARXFH8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-IqJpiyVN_EE','♪ Nagi Seishiro (Blue Lock) | Ego Morto | AniRap','IqJpiyVN_EE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-mXj_KIy9pqY','♪ Thanos (Round 6) | Let','mXj_KIy9pqY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-U2cqU6kt1QM','♪ Garou (One Punch Man) | Cosmic Monster | AniRap e @OkabeOficial','U2cqU6kt1QM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-2Lf-77Wj9ik','♪ Gun Park (Lookism) | Demônio Branco | AniRap','2Lf-77Wj9ik',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-X0i_if7cL9A','♪ Bastard X Barcha (Blue Lock) | Liga Neo Egoísta PT 1 | AniRap','X0i_if7cL9A',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-er1lYOaYxtk','♪ Itoshi Rin (Blue Lock) | ABSOLUTA DESTRUIÇÃO | AniRap','er1lYOaYxtk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-UnrFEfUFeVo','♪ E-Soul (To Be Hero X) | Trovão | AniRap & @OkabeOficial','UnrFEfUFeVo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-C4cMAFE-cSE','♪ Guerra Invencível (Invencível) | AniRap','C4cMAFE-cSE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-2JkEcrPd67k','♪ Nice/Lin Ling (To Be Hero X) | Perfeição | AniRap e @VMZoficial','2JkEcrPd67k',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-zx--rVw3dx0','♪ Mark Sinistro (Invencivel) | Pior Versão | AniRap','zx--rVw3dx0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-aPK-8FxU2ho','♪ Don Lorenzo (Blue Lock) | Dead-Rich | AniRap','aPK-8FxU2ho',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-RLwKq6iyCbs','♪ Sun Wukong (Shuumatsu no Valkyrie - Gods','RLwKq6iyCbs',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-yH4JxzMbKXk','♪ Mortes 2 | Shuumatsu no Valkyrie | AniRap','yH4JxzMbKXk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-pXAW-il31LQ','♪ Ban (Nanatsu no Taizai) | Morto-Vivo | AniRap','pXAW-il31LQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-0LM1n6LSFIY','♪ Yujiro Hanma (Baki The Grappler) | Demon Back | AniRap','0LM1n6LSFIY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-h7L_qBZ9YM8','♪ Mark Moicano (Invencivel) | Herdeiro de Viltrum | AniRap','h7L_qBZ9YM8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-9Tg9abSxGWg','♪ Akaza, Douma e Kokushibo | Eclipse Carmesim | AniRap','9Tg9abSxGWg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-JcCUUW7mGCQ','♪ Okita Souji | Criança X Demônio | AniRap','JcCUUW7mGCQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-coTVGT-HTTo','♪ Sakamoto Taro | Lendario Assassino | AniRap','coTVGT-HTTo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-7L7Nap_o1qw','♪ CONQUISTA (BEAT OFICIAL)','7L7Nap_o1qw',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-CLGj2OYYnEk','♪ Conquista | INSTÁVEL | AniRap','CLGj2OYYnEk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-n_1blWMRmwk','♪ Dante | Devil Trigger | AniRap','n_1blWMRmwk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-JRjzkNS7HV0','♪ Diego Brando | Jurassic World | AniRap','JRjzkNS7HV0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-J_Bw-r4__IE','♪ Yasuke e Naoe (Assassin’s Creed Shadows) | Caminho da Vingança | AniRap e @danyellaaiko','J_Bw-r4__IE',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-g6TDNoeTFQA','♪ Itadori Yuji (Jujutsu Kaisen) | EU SOU VOCÊ | AniRap','g6TDNoeTFQA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-m2zDk8yS964','♪ Itachi Uchiha (Naruto) | Olhos Cansados  | AniRap','m2zDk8yS964',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-DxsT1I6F7VY','♪ Kokushibo (Kimetsu no Yaiba) | Inveja | AniRap','DxsT1I6F7VY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-bpolCF-IeJg','♪ Rath  (Ben 10) | Selvagem | AniRap','bpolCF-IeJg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-4vFyd_QlzEk','♪ Itoshi Sae (Blue Lock) | ABSOLUTO | AniRap','4vFyd_QlzEk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-TPMRurBpA8Y','♪ Lancelot (Mokushiroku no Yonkishi) | GUERRA | AniRap','TPMRurBpA8Y',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-v93mEY0x0NA','♪ Creepypastas | 𝘼𝙍𝙌𝙐𝙄𝙑𝙊 404 | AniRap','v93mEY0x0NA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-KgsWsBThrH0','AniRap - Chamas da Vida','KgsWsBThrH0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-zFT0B8-5gU8','♪ Okarun (Dandadan) | KRL, CADÊ MEU PA* | AniRap e @DYAOficial.','zFT0B8-5gU8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-USfFY2ACnm4','♪ SHINJUKU | Sukuna Vs Feiticeiros | AniRap','USfFY2ACnm4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-nR_ZZf7gy7I','♪ Ekko (Arcane) | Momentos | AniRap','nR_ZZf7gy7I',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-MWff93oddc0','♪ Barba Negra (One Piece) | Horizonte Obscuro | AniRap & @henriquemendonca','MWff93oddc0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-nDIbWGJ2zw8','♪ Hypno (Pokémon: Creepypasta) | Sonho | DROP URT','nDIbWGJ2zw8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-j111AX4URR8','♪ Desabafo: Satoru Gojo | Últimas Palavras | Feat: ‪Gabriel Rodrigues | AniRap','j111AX4URR8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-DuUy1XDlnGQ','♪ Sukuna (Jujutsu Kaisen) | ARMAGEDOM | AniRap','DuUy1XDlnGQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Qj97NDtaC1A','♪ Ranger Vermelho (Go Go Loser Ranger) | LUZES, SANGUE E AÇÃO | AniRap','Qj97NDtaC1A',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-Q7AfW9ziqec','♪ Deadpool (Finge que é Jujutsu) | Ado ado ado | AniRap','Q7AfW9ziqec',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ABmekCLhfuY','♪ Yoshikage Kira (Jojo','ABmekCLhfuY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-lMLwbtX2LJ4','♪ Mirai Gohan (Dragon Ball Z) | Luz do Futuro | AniRap','lMLwbtX2LJ4',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-E48zGxhaEjQ','♪  Perdas (Yuta, Obito e Yuu Otosaka) Feat: ‪@VMZoficial e @TakaB','E48zGxhaEjQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-OWwQM8bxr-o','♪ Rudo Surebrec (Gachiakuta) | Lixo | AniRap','OWwQM8bxr-o',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-J9SnE66xqtc','♪ Feedback ( Ben 10 ) | Vício | AniRap','J9SnE66xqtc',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-k_eqAl10ghM','♪ Brutal (Sukuna, Dio e Yujiro) | AniRap | Feat: Daarui, M4rkim e Henrique M.','k_eqAl10ghM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-K1cyKfR944o','♪ Bam (Tower of God) | Irregular | AniRap','K1cyKfR944o',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-LD_sQFLQft8','♪ Michael Kaiser (Blue Lock)| O Melhor | AniRap','LD_sQFLQft8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-0PnC0YVfm60','♪ Douma (Kimetsu no Yaiba) | Frias Emoções | AniRap','0PnC0YVfm60',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-w6-vHsDOgrQ','♪ Gambit (X-Men ','w6-vHsDOgrQ',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-9zRqbnxr7m8','♪ Scooby Dark (Scooby Doo AU) | Último Mistério | AniRap','9zRqbnxr7m8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-jmdtZCkLFCg','♪ Fantasmático (Ben 10) | Medo | AniRap & Ishida','jmdtZCkLFCg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-tyvEP-owBo8','♪ Jo Togame (Wind Breaker) | Força Absoluta | AniRap','tyvEP-owBo8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-cn1mx_7lCiM','♪ Yuta Okkotsu (Jujutsu Kaisen) | AMOR | AniRap','cn1mx_7lCiM',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-f0cbC39pRyo','♪ Evolução (DBS) | Goku, Vegeta e Gohan | AniRap | Feat: Okabe, Ishida e Shooter','f0cbC39pRyo',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-pglwYbvebTI','♪ Mortes | Jujutsu Kaisen | AniRap','pglwYbvebTI',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-f8tNxNboPf8','♪ Sakura Haruka (Wind Breaker) | Sangue Ruim | AniRap','f8tNxNboPf8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-x9I0MDKhv9U','♪ Shuji Hanma | Pecado ou Punição | AniRap','x9I0MDKhv9U',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-iWPETOQx7Ag','♪ Shuji Hanma | Pecado ou Punição | AniRap (Prévia)','iWPETOQx7Ag',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-vetXTsLBClg','♪ Beyond Birthday (Death Note) | Eu Venci | AniRap','vetXTsLBClg',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ul1DVR0j9H0','♪ Beyond Birthday (Death Note) | Eu Venci | AniRap (Prévia)','ul1DVR0j9H0',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-mslaAj0cyEA','♪ Plano Perfeito | Death Note | URT','mslaAj0cyEA',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-ifDpM3M2mk8','♪ Plano Perfeito | Death Note | AniRap (Prévia)','ifDpM3M2mk8',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-FyADa6HiXXk','♪ Ben 10 (Carnitrix) | Primitivo | AniRap','FyADa6HiXXk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-odV30hDcRuk','♪ Beelzebub (Parte 2) | Amaldiçoado a Viver | AniRap','odV30hDcRuk',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true),
('anirap-kF0XPp4bKlY','♪ Skull and Bones | Filho do Mar | AniRap','kF0XPp4bKlY',0,'ANIRAP','ANIRAP',NULL,NULL,NULL,NULL,NULL,true)
ON CONFLICT (youtube_id) DO NOTHING;